/* GENERATED by tools/transpile_rig.py from pixelgoblin/gen/rig.py. Do not edit.
   Gate B13 regenerates this file and fails if the committed copy differs. */

function build_shapes(g, px, pose, style_px = null) {
  let H, top, tier, head_h, head_w, bob, hunch, head_cy, leg_len, hip_y, neck_y, sh_y, tw, torso_h, s, acc, top_kind, bottom, long_robe, back, leg_r, lx, foot_h, lift_l, lift_r, ta, arm_r, swing, hands, ear_len, ear_w, fx, knee, hem, mat, sx, sy, hx, hy, bx, tip, x, end_y, y, wide;
  H = g["height"];
  top = (GROUND - H);
  tier = F(D, (style_px || px));
  head_h = F((H * (g["head_pct"] + get(TIER_HEAD, tier, 0))), 100);
  head_w = F((head_h * g["head_w_pct"]), 100);
  bob = (get(pose, "bob", 0) * px);
  hunch = (g["hunch"] * px);
  head_cy = (((top + F(head_h, 2)) + bob) + hunch);
  leg_len = F((H * g["leg_pct"]), 100);
  hip_y = (GROUND - leg_len);
  neck_y = (((top + head_h) - F(head_h, 10)) + bob);
  sh_y = (neck_y + F(head_h, 10));
  tw = F((head_w * BUILDS[g["build"]]), 100);
  torso_h = (hip_y - sh_y);
  s = [];
  acc = Array.from(new Set(g["accessories"]));
  [top_kind, bottom] = [g["top"], g["bottom"]];
  long_robe = (["robe"].includes(top_kind));
  back = g["back"];
  if (((back === "cape")) || ((top_kind === "cloak"))) {
    s.push(T((CX - F((tw * 55), 100)), sh_y, (CX + F((tw * 55), 100)), sh_y, (CX + F((tw * 80), 100)), (hip_y + F((leg_len * 70), 100)), "cloth_a", 2, "back.large"));
    s.push(T((CX - F((tw * 55), 100)), sh_y, (CX - F((tw * 80), 100)), (hip_y + F((leg_len * 70), 100)), (CX + F((tw * 80), 100)), (hip_y + F((leg_len * 70), 100)), "cloth_a", 2, "back.large"));
  }
  if ((back === "backpack")) {
    s.push(R((CX - F((tw * 72), 100)), ((sh_y - F(head_h, 8)) + bob), (CX + F((tw * 72), 100)), (hip_y - F(torso_h, 10)), F(tw, 8), "leather", 2, "back.large"));
    s.push(R((CX - F((tw * 30), 100)), ((sh_y - F((head_h * 30), 100)) + bob), (CX + F((tw * 30), 100)), ((sh_y - F(head_h, 10)) + bob), F(tw, 10), "cloth_b", 3, "back"));
  }
  if ((back === "big_pack")) {
    s.push(R((CX - F((tw * 70), 100)), ((sh_y - F((head_h * 55), 100)) + bob), (CX + F((tw * 70), 100)), hip_y, F(tw, 6), "leather", 2, "back.large"));
    s.push(E((CX - F((tw * 40), 100)), ((sh_y - F((head_h * 55), 100)) + bob), F((tw * 20), 100), F((tw * 16), 100), "brass", 3, "back"));
    s.push(E((CX + F((tw * 45), 100)), ((sh_y - F((head_h * 50), 100)) + bob), F((tw * 16), 100), F((tw * 20), 100), "wood", 3, "back"));
  }
  if ((back === "quiver")) {
    s.push(C((CX + F((tw * 30), 100)), ((sh_y - F((head_h * 30), 100)) + bob), (CX - F((tw * 25), 100)), (hip_y - F(torso_h, 6)), F((tw * 13), 100), "leather", 2, "back.large"));
    for (let i = 0; i < 3; i++) {
      x = (CX + F((tw * (22 + (i * 9))), 100));
      s.push(T((x - F((tw * 5), 100)), ((sh_y - F((head_h * 30), 100)) + bob), (x + F((tw * 5), 100)), ((sh_y - F((head_h * 30), 100)) + bob), x, ((sh_y - F((head_h * 48), 100)) + bob), "metal", 3, "back"));
    }
  }
  if ((back === "fur")) {
    s.push(E(CX, (sh_y + F(torso_h, 6)), F((tw * 70), 100), F((torso_h * 45), 100), "fur", 3, "back.large"));
  }
  if ((g["hair"] === "long")) {
    s.push(E(CX, (head_cy + F((head_h * 25), 100)), F((head_w * 52), 100), F((head_h * 62), 100), "hair", 4, "hair"));
  }
  if ((g["hair"] === "ponytail")) {
    s.push(C((CX + F((head_w * 30), 100)), (head_cy - F((head_h * 20), 100)), (CX + F((head_w * 50), 100)), (head_cy + F((head_h * 55), 100)), F((head_w * 12), 100), "hair", 4, "hair"));
  }
  leg_r = Math.max(F((tw * 15), 100), F(px, 2));
  lx = Math.max(F((tw * 27), 100), ((leg_r + F(px, 2)) + px));
  foot_h = Math.max(leg_r, px);
  [lift_l, lift_r] = [(get(pose, "lift_l", 0) * px), (get(pose, "lift_r", 0) * px)];
  for (const [side, lift] of [[(-1), lift_l], [1, lift_r]]) {
    fx = (CX + (side * lx));
    s.push(C((CX + (side * lx)), (hip_y - F(leg_r, 2)), fx, ((GROUND - foot_h) - lift), leg_r, "skin", 10, "legs"));
    s.push(E((fx + F((side * leg_r), 3)), ((GROUND - F(foot_h, 2)) - lift), F((leg_r * 14), 10), (F((foot_h * 6), 10) + 1), "leather", (((tier >= 32)) ? 12 : 60), "feet"));
  }
  if (((bottom === "trousers")) || ((bottom === "shorts"))) {
    knee = (hip_y + (((bottom === "trousers")) ? F((leg_len * 45), 100) : F((leg_len * 30), 100)));
    for (const [side, lift] of [[(-1), lift_l], [1, lift_r]]) {
      end_y = (((bottom === "trousers")) ? ((GROUND - (foot_h * 2)) - lift) : knee);
      s.push(C((CX + (side * lx)), (hip_y - F(leg_r, 2)), (CX + (side * lx)), end_y, F((leg_r * 12), 10), "cloth_b", 14, "bottom"));
    }
    s.push(R(((CX - lx) - leg_r), (hip_y - leg_r), ((CX + lx) + leg_r), (hip_y + F(leg_r, 2)), F(leg_r, 2), "cloth_b", 14, "bottom"));
  }
  if (["skirt", "kilt"].includes(bottom)) {
    hem = (hip_y + F((leg_len * (((bottom === "skirt")) ? 55 : 35)), 100));
    mat = (((bottom === "skirt")) ? "cloth_b" : "leather");
    s.push(T((CX - F((tw * 45), 100)), (hip_y - leg_r), (CX + F((tw * 45), 100)), (hip_y - leg_r), (CX + F((tw * 62), 100)), hem, mat, 15, "bottom"));
    s.push(T((CX - F((tw * 45), 100)), (hip_y - leg_r), (CX - F((tw * 62), 100)), hem, (CX + F((tw * 62), 100)), hem, mat, 15, "bottom"));
  }
  s.push(R((CX - F(tw, 2)), (sh_y + bob), (CX + F(tw, 2)), (hip_y + leg_r), F((tw * 30), 100), "skin", 20, "torso"));
  ta = "cloth_a";
  if (["tunic", "crop", "wrap", "cloak"].includes(top_kind)) {
    hem = (hip_y + (((top_kind === "tunic")) ? F((leg_len * 30), 100) : (((top_kind === "crop")) ? F((-torso_h), 4) : leg_r)));
    s.push(R((CX - F((tw * 54), 100)), ((sh_y + bob) - px), (CX + F((tw * 54), 100)), hem, F((tw * 28), 100), ta, 22, "top"));
    if ((top_kind === "wrap")) {
      s.push(C((CX - F((tw * 45), 100)), (sh_y + bob), (CX + F((tw * 40), 100)), (hip_y - F(torso_h, 6)), F((tw * 10), 100), "cloth_b", 23, "pattern"));
    }
  } else if ((top_kind === "vest")) {
    s.push(R((CX - F((tw * 54), 100)), ((sh_y + bob) - px), (CX - F((tw * 10), 100)), (hip_y + leg_r), F((tw * 20), 100), ta, 22, "top"));
    s.push(R((CX + F((tw * 10), 100)), ((sh_y + bob) - px), (CX + F((tw * 54), 100)), (hip_y + leg_r), F((tw * 20), 100), ta, 22, "top"));
    s.push(R((CX - F((tw * 12), 100)), (sh_y + bob), (CX + F((tw * 12), 100)), hip_y, F(tw, 20), "cloth_b", 21, "top"));
  } else if (["robe", "dress"].includes(top_kind)) {
    hem = (((top_kind === "robe")) ? (GROUND - foot_h) : (hip_y + F((leg_len * 55), 100)));
    wide = F((tw * (((top_kind === "robe")) ? 70 : 78)), 100);
    s.push(R((CX - F((tw * 54), 100)), ((sh_y + bob) - px), (CX + F((tw * 54), 100)), hip_y, F((tw * 28), 100), ta, 22, "top"));
    s.push(T((CX - F((tw * 50), 100)), (hip_y - F(torso_h, 4)), (CX + F((tw * 50), 100)), (hip_y - F(torso_h, 4)), (CX + wide), hem, ta, 23, "top"));
    s.push(T((CX - F((tw * 50), 100)), (hip_y - F(torso_h, 4)), (CX - wide), hem, (CX + wide), hem, ta, 23, "top"));
    s.push(C(CX, ((sh_y + bob) + F(torso_h, 5)), CX, (hem - px), Math.max(F((tw * 5), 100), 1), "cloth_b", 24, "pattern"));
  } else if ((top_kind === "apron")) {
    s.push(R((CX - F((tw * 54), 100)), ((sh_y + bob) - px), (CX + F((tw * 54), 100)), (hip_y + leg_r), F((tw * 28), 100), "cloth_b", 22, "top"));
    s.push(R((CX - F((tw * 40), 100)), ((sh_y + bob) + F(torso_h, 4)), (CX + F((tw * 40), 100)), (hip_y + F((leg_len * 55), 100)), F(tw, 10), "leather", 25, "top"));
  } else if ((top_kind === "armor_light")) {
    s.push(R((CX - F((tw * 55), 100)), ((sh_y + bob) - px), (CX + F((tw * 55), 100)), (hip_y + leg_r), F((tw * 25), 100), "leather", 22, "top"));
    s.push(C((CX - F((tw * 45), 100)), (sh_y + bob), (CX + F((tw * 45), 100)), (hip_y - F(torso_h, 8)), Math.max(F((tw * 7), 100), 1), "cloth_a", 23, "straps"));
  } else if ((top_kind === "armor_heavy")) {
    s.push(R((CX - F((tw * 58), 100)), ((sh_y + bob) - px), (CX + F((tw * 58), 100)), (hip_y + F((leg_len * 25), 100)), F((tw * 22), 100), "metal", 22, "top"));
    s.push(R((CX - F((tw * 30), 100)), ((sh_y + bob) + F(torso_h, 5)), (CX + F((tw * 30), 100)), (hip_y - F(torso_h, 8)), F(tw, 10), "cloth_a", 23, "pattern"));
  } else if ((top_kind === "fur_mantle")) {
    s.push(R((CX - F((tw * 54), 100)), ((sh_y + bob) - px), (CX + F((tw * 54), 100)), (hip_y + leg_r), F((tw * 28), 100), ta, 22, "top"));
  }
  if (((top_kind === "fur_mantle")) || (("fur" === back))) {
    s.push(E(CX, ((sh_y + bob) + F(torso_h, 10)), F((tw * 68), 100), F((torso_h * 28), 100), "fur", 26, "top"));
  }
  if (["backpack", "big_pack", "quiver"].includes(back)) {
    for (const side of [(-1), 1]) {
      s.push(C((CX + F(((side * tw) * 30), 100)), (sh_y + bob), (CX + F(((side * tw) * 26), 100)), (hip_y - F(torso_h, 4)), Math.max(F(px, 2), F(tw, 16)), "leather", 27, "straps", {snap: true}));
    }
  }
  if ((acc.includes("belt")) || (["tunic", "robe", "armor_light", "apron"].includes(top_kind))) {
    s.push(R((CX - F((tw * 55), 100)), (hip_y - F(torso_h, 8)), (CX + F((tw * 55), 100)), ((hip_y - F(torso_h, 8)) + Math.max(F(torso_h, 9), px)), F(px, 2), "leather", 27, "belt", {snap: true}));
    s.push(R((CX - F((tw * 9), 100)), ((hip_y - F(torso_h, 8)) - F(px, 2)), (CX + F((tw * 9), 100)), (((hip_y - F(torso_h, 8)) + Math.max(F(torso_h, 9), px)) + F(px, 2)), F(px, 2), "brass", 28, "buckle"));
  }
  if (acc.includes("pouches")) {
    for (const side of [(-1), 1]) {
      s.push(R(((CX + F(((side * tw) * 35), 100)) - F(tw, 10)), (hip_y - F(torso_h, 10)), ((CX + F(((side * tw) * 35), 100)) + F(tw, 10)), (hip_y + F(torso_h, 10)), F(tw, 20), "leather", 29, "pouches"));
    }
  }
  if (acc.includes("necklace")) {
    s.push(A(CX, (sh_y + bob), F((tw * 32), 100), F((torso_h * 30), 100), Math.max(px, F(torso_h, 25)), 1, "brass", 28, "necklace"));
    s.push(E(CX, ((sh_y + bob) + F((torso_h * 30), 100)), F((tw * 6), 100), F((tw * 6), 100), "gem", 29, "necklace"));
  }
  if (acc.includes("scarf")) {
    s.push(R((CX - F((tw * 45), 100)), ((sh_y + bob) - F(head_h, 12)), (CX + F((tw * 45), 100)), ((sh_y + bob) + F(head_h, 12)), F(tw, 10), "cloth_b", 29, "scarf"));
    s.push(C((CX + F((tw * 20), 100)), (sh_y + bob), (CX + F((tw * 30), 100)), ((sh_y + bob) + F((torso_h * 45), 100)), F((tw * 8), 100), "cloth_b", 29, "scarf"));
  }
  if (acc.includes("pauldrons")) {
    for (const side of [(-1), 1]) {
      s.push(E((CX + F(((side * tw) * 50), 100)), ((sh_y + bob) + F(head_h, 20)), F((tw * 28), 100), F((tw * 20), 100), "metal", 36, "pauldrons"));
    }
  }
  if (acc.includes("tattoo")) {
    for (let i = 0; i < 2; i++) {
      y = ((sh_y + bob) + F((torso_h * (30 + (i * 18))), 100));
      s.push(C((CX - F((tw * 42), 100)), y, (CX - F((tw * 20), 100)), (y + px), Math.max(F(px, 2), 1), "arcane", 24, "pattern"));
    }
  }
  arm_r = Math.max(F((tw * 12), 100), F(px, 2));
  swing = (get(pose, "swing", 0) * px);
  hands = ({});
  for (const side of [(-1), 1]) {
    [sx, sy] = [(CX + (side * (F(tw, 2) - F(arm_r, 2)))), ((sh_y + bob) + arm_r)];
    hx = (CX + (side * (F(tw, 2) + F((tw * 14), 100))));
    hy = (((hip_y + arm_r) + (side * swing)) + bob);
    s.push(C(sx, sy, hx, hy, arm_r, "skin", 30, "arms"));
    if (["tunic", "robe", "dress", "fur_mantle", "armor_heavy", "cloak", "wrap"].includes(top_kind)) {
      mat = (((top_kind === "armor_heavy")) ? "metal" : ta);
      s.push(C(sx, sy, F((sx + hx), 2), F((sy + hy), 2), F((arm_r * 12), 10), mat, 31, "sleeves"));
    }
    if (acc.includes("bracers")) {
      s.push(C(F((sx + (2 * hx)), 3), F((sy + (2 * hy)), 3), hx, (hy - arm_r), F((arm_r * 11), 10), "leather", 31, "bracers"));
    }
    s.push(E(hx, hy, F((arm_r * 13), 10), F((arm_r * 13), 10), "skin", 33, "hands"));
    hands[side] = [hx, hy];
  }
  _held(s, g["held"], hands[(-1)], (-1), tw, head_h, px);
  _held(s, g["offhand"], hands[1], 1, tw, head_h, px);
  ear_len = Math.min(F((head_w * g["ear_len"]), 100), (496 - F(head_w, 2)));
  ear_w = F((head_h * g["ear_w"]), 100);
  for (const side of [(-1), 1]) {
    bx = (CX + F(((side * head_w) * 38), 100));
    tip = [(CX + (side * (F(head_w, 2) + ear_len))), (head_cy - F((head_h * g["ear_lift"]), 100))];
    s.push(T(bx, (head_cy - F((ear_w * 6), 10)), bx, (head_cy + F((ear_w * 4), 10)), tip[0], tip[1], "skin", 40, "ears", {snap: true}));
    s.push(T((bx + F((side * head_w), 20)), (head_cy - F((ear_w * 3), 10)), (bx + F((side * head_w), 20)), (head_cy + F(ear_w, 5)), (CX + (side * (F(head_w, 2) + F((ear_len * 7), 10)))), (tip[1] + F((head_cy - tip[1]), 5)), "skin", 41, "ear_inner", {bias: (-1)}));
    if (acc.includes("earrings")) {
      s.push(A((bx + F((side * ear_len), 3)), (head_cy + F((ear_w * 3), 10)), F(head_w, 14), F(head_w, 14), Math.max(px, F(head_w, 40)), 0, "brass", 42, "earrings"));
    }
    if (acc.includes("fins")) {
      s.push(T((bx + F((side * ear_len), 4)), (head_cy - ear_w), (bx + (side * ear_len)), (head_cy - F((ear_w * 14), 10)), (bx + F(((side * ear_len) * 7), 10)), (head_cy - F(ear_w, 5)), "arcane", 39, "fins"));
    }
  }
  s.push(E(CX, head_cy, F(head_w, 2), F(head_h, 2), "skin", 44, "head"));
  s.push(E(CX, (head_cy + F(head_h, 6)), F((head_w * 40), 100), F((head_h * 40), 100), "skin", 44, "head"));
  _face(s, g, head_cy, head_w, head_h, px, pose, (style_px || px));
  _hair(s, g["hair"], head_cy, head_w, head_h, px);
  _headwear(s, g["headwear"], head_cy, head_w, head_h, px);
  if (acc.includes("glasses")) {
    for (const side of [(-1), 1]) {
      s.push(A((CX + F(((side * head_w) * 20), 100)), (head_cy + F((head_h * 4), 100)), F((head_w * 14), 100), F((head_h * 12), 100), Math.max(px, F(head_w, 40)), 0, "brass", 56, "glasses", {snap: true}));
    }
  }
  if ((acc.includes("goggles")) && ((g["headwear"] !== "goggles"))) {
    _goggles(s, (head_cy - F((head_h * 30), 100)), head_w, head_h, px, 57);
  }
  return s;
}

function _goggles(s, y, head_w, head_h, px, z) {
  s.push(R((CX - F((head_w * 50), 100)), (y - F(head_h, 22)), (CX + F((head_w * 50), 100)), (y + F(head_h, 22)), F(px, 2), "leather", z, "goggles", {snap: true}));
  for (const side of [(-1), 1]) {
    s.push(E((CX + F(((side * head_w) * 20), 100)), y, F((head_w * 14), 100), F((head_h * 11), 100), "brass", (z + 1), "goggles"));
    s.push(E((CX + F(((side * head_w) * 20), 100)), y, F((head_w * 9), 100), F((head_h * 7), 100), "gem", (z + 2), "highlights"));
  }
}

function _face(s, g, cy, hw, hh, px, pose, style_px) {
  let ey, boost, erx, ery, ex_off, expr, blink, my, mw, th, ex, wink, tilt, lift, by, inner, outer, r, off;
  ey = (cy + F((hh * 4), 100));
  boost = (100 + get(TIER_EYE, F(D, style_px), 0));
  [erx, ery] = [F((((hw * 10) * g["eye"]) * boost), 1000000), F((((hh * 9) * g["eye"]) * boost), 1000000)];
  ex_off = Math.max(F((hw * 21), 100), (Math.max(erx, F(px, 2)) + px));
  expr = g["expression"];
  blink = get(pose, "blink", 0);
  for (const side of [(-1), 1]) {
    ex = (CX + (side * ex_off));
    wink = (((expr === "playful")) && ((side === 1)));
    if (blink || wink) {
      s.push(C((ex - erx), ey, (ex + erx), ey, Math.max(F(px, 2), F(hh, 60)), "mouth", 50, "eyes", {snap: true}));
      continue;
    }
    s.push(E(ex, ey, erx, ery, "iris", 50, "eyes", {snap: true}));
    s.push(E(ex, ey, erx, ery, "eye_white", 51, "eye_whites"));
    s.push(E((ex + F((side * erx), 5)), ey, F((erx * 60), 100), F((ery * 70), 100), "iris", 52, "eye_whites"));
    s.push(E((ex + F((side * erx), 5)), ey, F((erx * 28), 100), F((ery * 36), 100), "mouth", 53, "pupils"));
    s.push(E((ex - F(erx, 3)), (ey - F(ery, 3)), (F(erx, 5) + 1), (F(ery, 5) + 1), "eye_white", 54, "highlights"));
    tilt = get(({["angry"]: 3, ["annoyed"]: 2, ["surprised"]: (-2), ["thoughtful"]: (((side === 1)) ? 1 : 0)}), expr, 0);
    lift = ((((expr === "surprised")) || (((expr === "curious")) && ((side === (-1))))) ? F((hh * 5), 100) : 0);
    by = (((ey - ery) - F((hh * 7), 100)) - lift);
    [inner, outer] = [(ex - F(((side * erx) * 12), 10)), (ex + F(((side * erx) * 12), 10))];
    s.push(C(inner, (by + F((tilt * hh), 60)), outer, by, Math.max(F(px, 2), F(hh, 50)), "hair", 55, "brows"));
  }
  s.push(E(CX, (cy + F((hh * 18), 100)), F(((hw * 9) * g["nose"]), 10000), F(((hh * 15) * g["nose"]), 10000), "skin", 52, "nose", {bias: (-1)}));
  s.push(E((CX - F((hw * 2), 100)), (cy + F((hh * 15), 100)), F(((hw * 4) * g["nose"]), 10000), F(((hh * 7) * g["nose"]), 10000), "skin", 53, "highlights", {bias: 1}));
  [my, mw] = [(cy + F((hh * 33), 100)), F((hw * 22), 100)];
  th = Math.max(px, F(hh, 40));
  if (["happy", "playful"].includes(expr)) {
    s.push(A(CX, (my - F((hh * 6), 100)), mw, F((hh * 10), 100), th, 1, "mouth", 53, "mouth", {snap: true}));
    if ((expr === "playful")) {
      s.push(E((CX + F(mw, 3)), (my + F((hh * 5), 100)), F(mw, 4), F((hh * 5), 100), "mouth", 54, "tongue", {bias: 2}));
    }
  } else if ((expr === "angry")) {
    s.push(A(CX, (my + F((hh * 7), 100)), mw, F((hh * 9), 100), th, (-1), "mouth", 53, "mouth", {snap: true}));
    for (const side of [(-1), 1]) {
      s.push(T((CX + F(((side * mw) * 6), 10)), (my - th), (CX + F(((side * mw) * 3), 10)), (my - th), (CX + F(((side * mw) * 45), 100)), (my - F((hh * 9), 100)), "teeth", 54, "tusks"));
    }
  } else if (((expr === "surprised")) || ((expr === "curious"))) {
    r = F((mw * (((expr === "surprised")) ? 45 : 28)), 100);
    s.push(E(CX, my, r, F((r * 12), 10), "mouth", 53, "mouth", {snap: true}));
  } else if ((expr === "confident")) {
    s.push(A((CX + F(mw, 3)), (my - F((hh * 5), 100)), F((mw * 7), 10), F((hh * 8), 100), th, 1, "mouth", 53, "mouth", {snap: true}));
    s.push(T((CX - F((mw * 5), 10)), my, (CX - F((mw * 3), 10)), my, (CX - F((mw * 4), 10)), (my - F((hh * 9), 100)), "teeth", 54, "tusks"));
  } else {
    off = (((expr === "thoughtful")) ? F(mw, 4) : 0);
    s.push(C(((CX - F((mw * 7), 10)) + off), my, ((CX + F((mw * 7), 10)) + off), (my + (((expr === "annoyed")) ? F(hh, 60) : 0)), (F(th, 2) + 1), "mouth", 53, "mouth", {snap: true}));
  }
  if ((g["accessories"].includes("tusks")) && ((expr !== "angry"))) {
    for (const side of [(-1), 1]) {
      s.push(T((CX + F(((side * mw) * 6), 10)), (my + th), (CX + F(((side * mw) * 3), 10)), (my + th), (CX + F(((side * mw) * 45), 100)), (my - F((hh * 8), 100)), "teeth", 54, "tusks"));
    }
  }
  if (g["accessories"].includes("beard")) {
    s.push(T((CX - F((hw * 34), 100)), (cy + F((hh * 26), 100)), (CX + F((hw * 34), 100)), (cy + F((hh * 26), 100)), CX, (cy + F((hh * 95), 100)), "hair", 56, "beard"));
    s.push(E(CX, (cy + F((hh * 45), 100)), F((hw * 32), 100), F((hh * 22), 100), "hair", 56, "beard"));
    s.push(C((CX - F((hw * 25), 100)), (cy + F((hh * 28), 100)), (CX + F((hw * 25), 100)), (cy + F((hh * 28), 100)), F(hh, 18), "hair", 57, "beard"));
  }
}

function _hair(s, style, cy, hw, hh, px) {
  let top;
  top = (cy - F(hh, 2));
  if ((style === "none")) {
    return;
  }
  if (["short", "wild", "braids", "twintails", "long", "ponytail", "bun", "topknot"].includes(style)) {
    s.push(A(CX, (cy - F(hh, 10)), F((hw * 51), 100), F((hh * 44), 100), F((hh * 16), 100), (-1), "hair", 58, "hair"));
  }
  if ((style === "topknot")) {
    s.push(E(CX, (top - F(hh, 10)), F((hw * 16), 100), F((hh * 16), 100), "hair", 58, "hair", {snap: true}));
  }
  if ((style === "bun")) {
    s.push(E(CX, (top + F(hh, 20)), F((hw * 22), 100), F((hh * 18), 100), "hair", 57, "hair"));
  }
  if ((style === "mohawk")) {
    s.push(E(CX, (top + F(hh, 20)), F((hw * 10), 100), F((hh * 30), 100), "hair", 58, "hair", {snap: true}));
  }
  if ((style === "wild")) {
    for (let i = (-2); i < 3; i++) {
      s.push(T(((CX + F(((i * hw) * 18), 100)) - F(hw, 10)), (top + F(hh, 6)), ((CX + F(((i * hw) * 18), 100)) + F(hw, 10)), (top + F(hh, 6)), (CX + F(((i * hw) * 24), 100)), ((top - F(hh, 6)) - F((Math.abs(i) * hh), 30)), "hair", 59, "hair"));
    }
  }
  if (((style === "braids")) || ((style === "twintails"))) {
    for (const side of [(-1), 1]) {
      if ((style === "braids")) {
        s.push(C((CX + F(((side * hw) * 45), 100)), cy, (CX + F(((side * hw) * 50), 100)), (cy + F((hh * 70), 100)), F((hw * 8), 100), "hair", 59, "hair", {snap: true}));
      } else {
        s.push(E((CX + F(((side * hw) * 55), 100)), (cy - F((hh * 10), 100)), F((hw * 16), 100), F((hh * 30), 100), "hair", 43, "hair"));
      }
    }
  }
}

function _headwear(s, kind, cy, hw, hh, px) {
  let top, z;
  top = (cy - F(hh, 2));
  z = 60;
  if ((kind === "hood")) {
    s.push(A(CX, (cy + F(hh, 10)), F((hw * 58), 100), F((hh * 62), 100), F((hh * 20), 100), (-1), "cloth_a", z, "headwear.large"));
    s.push(T((CX - F(hw, 5)), (top - F(hh, 20)), (CX + F(hw, 5)), (top - F(hh, 20)), (CX + F(hw, 4)), (top - F((hh * 30), 100)), "cloth_a", z, "headwear"));
  } else if ((kind === "bandana")) {
    s.push(R((CX - F((hw * 50), 100)), (cy - F((hh * 22), 100)), (CX + F((hw * 50), 100)), (cy - F((hh * 12), 100)), F(px, 2), "cloth_b", z, "headwear", {snap: true}));
    s.push(T((CX + F((hw * 45), 100)), (cy - F((hh * 18), 100)), (CX + F((hw * 70), 100)), (cy - F((hh * 5), 100)), (CX + F((hw * 62), 100)), (cy - F((hh * 30), 100)), "cloth_b", z, "headwear"));
  } else if ((kind === "goggles")) {
    _goggles(s, (cy - F((hh * 30), 100)), hw, hh, px, z);
  } else if ((kind === "helm")) {
    s.push(A(CX, (cy - F(hh, 20)), F((hw * 54), 100), F((hh * 50), 100), F((hh * 24), 100), (-1), "metal", z, "headwear.large"));
    s.push(R((CX - F(hw, 25)), (cy - F(hh, 5)), (CX + F(hw, 25)), (cy + F((hh * 12), 100)), F(px, 2), "metal", (z + 1), "headwear", {snap: true}));
  } else if ((kind === "feather_crown")) {
    s.push(R((CX - F((hw * 46), 100)), (cy - F((hh * 34), 100)), (CX + F((hw * 46), 100)), (cy - F((hh * 24), 100)), F(px, 2), "brass", z, "headwear", {snap: true}));
    for (let i = (-2); i < 3; i++) {
      s.push(C((CX + F(((i * hw) * 17), 100)), (cy - F((hh * 34), 100)), (CX + F(((i * hw) * 26), 100)), ((top - F((hh * 42), 100)) + F((Math.abs(i) * hh), 10)), F((hw * 5), 100), (MOD(i, 2) ? "cloth_a" : "fur"), (z - 1), "headwear.large", {snap: true}));
    }
  } else if ((kind === "chef_hat")) {
    s.push(E(CX, (top - F(hh, 8)), F((hw * 40), 100), F((hh * 30), 100), "paper", z, "headwear.large"));
    s.push(R((CX - F((hw * 36), 100)), (top - F(hh, 20)), (CX + F((hw * 36), 100)), (top + F(hh, 10)), F(hw, 20), "paper", (z + 1), "headwear"));
  } else if ((kind === "horns")) {
    for (const side of [(-1), 1]) {
      s.push(C((CX + F(((side * hw) * 25), 100)), (top + F(hh, 8)), (CX + F(((side * hw) * 55), 100)), (top - F((hh * 25), 100)), F((hw * 7), 100), "fur", z, "headwear.large", {snap: true}));
      s.push(C((CX + F(((side * hw) * 55), 100)), (top - F((hh * 25), 100)), (CX + F(((side * hw) * 45), 100)), (top - F((hh * 45), 100)), F((hw * 5), 100), "fur", z, "headwear.large", {snap: true}));
    }
    s.push(R((CX - F((hw * 46), 100)), (cy - F((hh * 34), 100)), (CX + F((hw * 46), 100)), (cy - F((hh * 24), 100)), F(px, 2), "leather", (z + 1), "headwear", {snap: true}));
  } else if ((kind === "flower_crown")) {
    s.push(A(CX, (cy - F(hh, 10)), F((hw * 50), 100), F((hh * 32), 100), Math.max(px, F(hh, 20)), (-1), "wood", z, "headwear", {snap: true}));
    for (let i = (-2); i < 3; i++) {
      s.push(E((CX + F(((i * hw) * 20), 100)), ((cy - F((hh * 35), 100)) - F(((2 - Math.abs(i)) * hh), 40)), F((hw * 6), 100), F((hw * 6), 100), (MOD(i, 2) ? "cloth_a" : "glow"), (z + 1), "flowers"));
    }
  } else if ((kind === "headscarf")) {
    s.push(A(CX, cy, F((hw * 54), 100), F((hh * 55), 100), F((hh * 20), 100), (-1), "cloth_b", z, "headwear.large"));
    s.push(T((CX + F((hw * 40), 100)), (cy - F(hh, 10)), (CX + F((hw * 62), 100)), (cy + F((hh * 30), 100)), (CX + F((hw * 30), 100)), (cy + F((hh * 25), 100)), "cloth_b", z, "headwear"));
  } else if ((kind === "cap")) {
    s.push(A(CX, (cy - F(hh, 12)), F((hw * 50), 100), F((hh * 44), 100), F((hh * 22), 100), (-1), "cloth_b", z, "headwear.large"));
  } else if ((kind === "circlet")) {
    s.push(R((CX - F((hw * 48), 100)), (cy - F((hh * 26), 100)), (CX + F((hw * 48), 100)), (cy - F((hh * 20), 100)), F(px, 2), "brass", z, "headwear", {snap: true}));
    s.push(E(CX, (cy - F((hh * 23), 100)), F((hw * 6), 100), F((hw * 6), 100), "gem", (z + 1), "headwear"));
  }
}

function _held(s, kind, hand, side, tw, hh, px) {
  let hx, hy, z, L, n, tipm;
  [hx, hy] = hand;
  z = 34;
  if ((kind === "none")) {
    return;
  }
  L = F((hh * 13), 10);
  if ((kind === "hammer")) {
    s.push(C(hx, (hy + F(L, 5)), (hx + F((side * L), 8)), (hy - F((L * 70), 100)), F(L, 16), "wood", z, "held.large", {snap: true}));
    s.push(R(((hx + F((side * L), 8)) - F(L, 5)), (hy - F((L * 85), 100)), ((hx + F((side * L), 8)) + F(L, 5)), (hy - F((L * 62), 100)), F(L, 30), "metal", (z + 1), "held.large"));
  } else if (["staff", "spear"].includes(kind)) {
    s.push(C(hx, (hy + F((L * 60), 100)), hx, (hy - F((L * 150), 100)), F(L, 18), "wood", z, "held.large", {snap: true}));
    if ((kind === "staff")) {
      s.push(E(hx, (hy - F((L * 158), 100)), F(L, 7), F(L, 7), "arcane", (z + 1), "held.large"));
      s.push(E((hx - F(L, 30)), (hy - F((L * 164), 100)), F(L, 20), F(L, 20), "glow", (z + 2), "highlights"));
    } else {
      s.push(T((hx - F(L, 10)), (hy - F((L * 145), 100)), (hx + F(L, 10)), (hy - F((L * 145), 100)), hx, (hy - F((L * 185), 100)), "metal", (z + 1), "held.large", {snap: true}));
    }
  } else if ((kind === "book")) {
    s.push(R(((hx - F(((side * L) * 5), 100)) - F(L, 4)), (hy - F(L, 3)), ((hx - F(((side * L) * 5), 100)) + F(L, 4)), (hy + F(L, 20)), F(L, 30), "leather", (z + 1), "held"));
    s.push(R(((hx - F(((side * L) * 5), 100)) - F(L, 5)), (hy - F((L * 29), 100)), ((hx - F(((side * L) * 5), 100)) + F(L, 5)), (hy + F(L, 60)), F(L, 60), "paper", (z + 2), "pattern"));
  } else if ((kind === "bow")) {
    s.push(A((hx - F((side * L), 8)), (hy - F(L, 4)), F(L, 3), F((L * 75), 100), Math.max(px, F(L, 18)), 0, "wood", z, "held.large", {snap: true}));
    s.push(R((((hx - F((side * L), 8)) - F(L, 3)) - F(L, 60)), (hy - L), (((hx - F((side * L), 8)) - F(L, 3)) + F(L, 60)), (hy + F(L, 2)), 0, "paper", (z - 1), "held"));
  } else if ((kind === "basket")) {
    s.push(E(hx, (hy + F(L, 10)), F((L * 35), 100), F((L * 25), 100), "wood", (z + 1), "held"));
    s.push(R((hx - F((L * 35), 100)), (hy - F(L, 20)), (hx + F((L * 35), 100)), (hy + F(L, 10)), F(L, 20), "wood", (z + 1), "held"));
    for (let i = (-1); i < 2; i++) {
      s.push(E((hx + F((i * L), 7)), (hy - F(L, 12)), F(L, 12), F(L, 12), (i ? "cloth_a" : "glow"), (z + 2), "flowers"));
    }
  } else if (["dagger", "sword"].includes(kind)) {
    n = (((kind === "dagger")) ? 60 : 120);
    s.push(T((hx - F(L, 18)), (hy - F(L, 12)), (hx + F(L, 18)), (hy - F(L, 12)), (hx + F((side * L), 20)), (hy - F((L * n), 100)), "metal", (z + 1), (((kind === "sword")) ? "held.large" : "held"), {snap: true}));
    s.push(R((hx - F(L, 7)), (hy - F(L, 12)), (hx + F(L, 7)), (hy - F(L, 20)), F(px, 2), "brass", (z + 2), "held"));
  } else if ((kind === "axe")) {
    s.push(C(hx, (hy + F(L, 5)), hx, (hy - F((L * 90), 100)), F(L, 16), "wood", z, "held.large", {snap: true}));
    s.push(T(hx, (hy - F((L * 95), 100)), hx, (hy - F((L * 55), 100)), (hx + F(((side * L) * 35), 100)), (hy - F((L * 75), 100)), "metal", (z + 1), "held.large"));
  } else if ((kind === "lute")) {
    s.push(C(hx, hy, (hx + F(((side * L) * 50), 100)), (hy - F((L * 70), 100)), F(L, 16), "wood", z, "held"));
    s.push(E((hx - F((side * L), 10)), (hy + F(L, 10)), F((L * 28), 100), F((L * 32), 100), "wood", (z + 1), "held.large"));
    s.push(E((hx - F((side * L), 10)), (hy + F(L, 20)), F(L, 12), F(L, 12), "leather", (z + 2), "pattern"));
  } else if ((kind === "lantern")) {
    s.push(C(hx, hy, hx, (hy + F(L, 5)), (F(L, 40) + 1), "metal", z, "held"));
    s.push(R((hx - F(L, 7)), (hy + F(L, 5)), (hx + F(L, 7)), (hy + F(L, 2)), F(L, 20), "brass", (z + 1), "held"));
    s.push(E(hx, (hy + F((L * 35), 100)), F(L, 12), F(L, 10), "glow", (z + 2), "held"));
  } else if (["ladle", "brush", "wrench", "whip"].includes(kind)) {
    s.push(C(hx, (hy + F(L, 6)), (hx + F((side * L), 5)), (hy - F((L * 65), 100)), F(L, 22), (((kind !== "wrench")) ? "wood" : "metal"), z, "held", {snap: true}));
    tipm = ({["ladle"]: "metal", ["brush"]: "cloth_a", ["wrench"]: "metal", ["whip"]: "leather"})[kind];
    s.push(E((hx + F((side * L), 5)), (hy - F((L * 70), 100)), F(L, 8), F(L, 10), tipm, (z + 1), "held"));
  } else if ((kind === "mug")) {
    s.push(R((hx - F(L, 7)), (hy - F(L, 5)), (hx + F(L, 7)), (hy + F(L, 8)), F(L, 25), "wood", (z + 1), "held"));
    s.push(E(hx, (hy - F(L, 5)), F(L, 7), F(L, 16), "paper", (z + 2), "held"));
  } else if ((kind === "teddy")) {
    s.push(E(hx, (hy + F(L, 12)), F(L, 6), F(L, 5), "fur", (z + 1), "held"));
    s.push(E(hx, (hy - F(L, 6)), F(L, 7), F(L, 8), "fur", (z + 1), "held"));
    for (const sd of [(-1), 1]) {
      s.push(E((hx + F((sd * L), 10)), (hy - F(L, 4)), F(L, 20), F(L, 20), "fur", (z + 1), "held"));
    }
  } else if (["scroll", "map"].includes(kind)) {
    s.push(R((hx - F(L, 4)), (hy - F(L, 6)), (hx + F(L, 4)), (hy + F(L, 20)), F(L, 40), "paper", (z + 1), "held"));
    s.push(C((hx - F(L, 4)), (hy - F(L, 6)), (hx - F(L, 4)), (hy + F(L, 20)), F(L, 25), "wood", (z + 2), "held"));
  } else if ((kind === "orb")) {
    s.push(E(hx, (hy - F(L, 6)), F(L, 6), F(L, 6), "arcane", (z + 1), "held.large"));
    s.push(E((hx - F(L, 20)), (hy - F(L, 5)), F(L, 18), F(L, 18), "glow", (z + 2), "highlights"));
  } else if ((kind === "bag")) {
    s.push(E(hx, (hy + F(L, 8)), F(L, 5), F(L, 5), "leather", (z + 1), "held"));
  } else if ((kind === "flask")) {
    s.push(E(hx, hy, F(L, 8), F(L, 7), "gem", (z + 1), "held"));
    s.push(R((hx - F(L, 30)), (hy - F(L, 4)), (hx + F(L, 30)), (hy - F(L, 9)), 0, "paper", (z + 1), "held", {snap: true}));
  } else if ((kind === "shield")) {
    s.push(E((hx - F((side * L), 12)), (hy - F(L, 6)), F((L * 36), 100), F((L * 42), 100), "wood", (z + 1), "held.large"));
    s.push(A((hx - F((side * L), 12)), (hy - F(L, 6)), F((L * 36), 100), F((L * 42), 100), Math.max(px, F(L, 20)), 0, "metal", (z + 2), "held"));
    s.push(E((hx - F((side * L), 12)), (hy - F(L, 6)), F(L, 12), F(L, 12), "brass", (z + 3), "held"));
  }
}
