/* GENERATED by tools/transpile_rig.py from pixelgoblin/gen/{rig,rig3d,beast}.py. Do not edit.
   Gate B13 regenerates this file and fails if the committed copy differs. */

// ---- from pixelgoblin/gen/rig.py
const SIGNATURE_ORDER = ["held", "headwear", "back", "beard", "top"];
const POW2_16 = [4096, 4277, 4467, 4664, 4871, 5087, 5312, 5547, 5793, 6049, 6317, 6597, 6889, 7194, 7512, 7845];
function build_shapes(g, px, pose, style_px = null) {
  let H, top, tier, head_h, head_w, bob, hunch, head_cy, leg_len, hip_y, neck_y, sh_y, tw, torso_h, s, acc, top_kind, bottom, long_robe, back, leg_r, lx, foot_h, lift_l, lift_r, side, lift, ta, arm_r, swing, hands, ear_len, ear_w, i, fx, knee, hem, mat, sx, sy, hx, hy, bx, tip, x, end_y, y, wide, _e1, _e2;
  H = g["height"];
  top = (GROUND - H);
  tier = F(D, (style_px || px));
  head_h = F((H * (g["head_pct"] + get(TIER_HEAD, tier, 0))), 100);
  head_w = F((head_h * g["head_w_pct"]), 100);
  bob = (get(pose, "bob", 0) * px);
  hunch = (g["hunch"] * px);
  head_cy = (((top + F(head_h, 2)) + bob) + hunch);
  leg_len = F((H * g["leg_pct"]), 100);
  hip_y = (GROUND - leg_len);
  neck_y = (((top + head_h) - F(head_h, 10)) + bob);
  sh_y = (neck_y + F(head_h, 10));
  tw = F((head_w * BUILDS[g["build"]]), 100);
  torso_h = (hip_y - sh_y);
  s = [];
  acc = Array.from(new Set(g["accessories"]));
  [top_kind, bottom] = [g["top"], g["bottom"]];
  long_robe = (["robe"].includes(top_kind));
  back = g["back"];
  if (((back === "cape")) || ((top_kind === "cloak"))) {
    s.push(T((CX - F((tw * 55), 100)), sh_y, (CX + F((tw * 55), 100)), sh_y, (CX + F((tw * 80), 100)), (hip_y + F((leg_len * 70), 100)), "cloth_a", 2, "back.large"));
    s.push(T((CX - F((tw * 55), 100)), sh_y, (CX - F((tw * 80), 100)), (hip_y + F((leg_len * 70), 100)), (CX + F((tw * 80), 100)), (hip_y + F((leg_len * 70), 100)), "cloth_a", 2, "back.large"));
  }
  if ((back === "backpack")) {
    s.push(R((CX - F((tw * 72), 100)), ((sh_y - F(head_h, 8)) + bob), (CX + F((tw * 72), 100)), (hip_y - F(torso_h, 10)), F(tw, 8), "leather", 2, "back.large"));
    s.push(R((CX - F((tw * 30), 100)), ((sh_y - F((head_h * 30), 100)) + bob), (CX + F((tw * 30), 100)), ((sh_y - F(head_h, 10)) + bob), F(tw, 10), "cloth_b", 3, "back"));
  }
  if ((back === "big_pack")) {
    s.push(R((CX - F((tw * 70), 100)), ((sh_y - F((head_h * 55), 100)) + bob), (CX + F((tw * 70), 100)), hip_y, F(tw, 6), "leather", 2, "back.large"));
    s.push(E((CX - F((tw * 40), 100)), ((sh_y - F((head_h * 55), 100)) + bob), F((tw * 20), 100), F((tw * 16), 100), "brass", 3, "back"));
    s.push(E((CX + F((tw * 45), 100)), ((sh_y - F((head_h * 50), 100)) + bob), F((tw * 16), 100), F((tw * 20), 100), "wood", 3, "back"));
  }
  if ((back === "quiver")) {
    s.push(C((CX + F((tw * 30), 100)), ((sh_y - F((head_h * 30), 100)) + bob), (CX - F((tw * 25), 100)), (hip_y - F(torso_h, 6)), F((tw * 13), 100), "leather", 2, "back.large"));
    for (i = 0, _e1 = 3; i < _e1; i += 1) {
      x = (CX + F((tw * (22 + (i * 9))), 100));
      s.push(T((x - F((tw * 5), 100)), ((sh_y - F((head_h * 30), 100)) + bob), (x + F((tw * 5), 100)), ((sh_y - F((head_h * 30), 100)) + bob), x, ((sh_y - F((head_h * 48), 100)) + bob), "metal", 3, "back"));
    }
  }
  if ((back === "fur")) {
    s.push(E(CX, (sh_y + F(torso_h, 6)), F((tw * 70), 100), F((torso_h * 45), 100), "fur", 3, "back.large"));
  }
  if ((g["hair"] === "long")) {
    s.push(E(CX, (head_cy + F((head_h * 25), 100)), F((head_w * 52), 100), F((head_h * 62), 100), "hair", 4, "hair"));
  }
  if ((g["hair"] === "ponytail")) {
    s.push(C((CX + F((head_w * 30), 100)), (head_cy - F((head_h * 20), 100)), (CX + F((head_w * 50), 100)), (head_cy + F((head_h * 55), 100)), F((head_w * 12), 100), "hair", 4, "hair"));
  }
  leg_r = Math.max(F((tw * 15), 100), F(px, 2));
  lx = Math.max(F((tw * 27), 100), ((leg_r + F(px, 2)) + px));
  foot_h = Math.max(leg_r, px);
  [lift_l, lift_r] = [(get(pose, "lift_l", 0) * px), (get(pose, "lift_r", 0) * px)];
  for ([side, lift] of [[(-1), lift_l], [1, lift_r]]) {
    fx = (CX + (side * lx));
    s.push(C((CX + (side * lx)), (hip_y - F(leg_r, 2)), fx, ((GROUND - foot_h) - lift), leg_r, "skin", 10, "legs"));
    s.push(E((fx + F((side * leg_r), 3)), ((GROUND - F(foot_h, 2)) - lift), F((leg_r * 14), 10), (F((foot_h * 6), 10) + 1), "leather", (((tier >= 32)) ? 12 : 200), "feet"));
  }
  if (((bottom === "trousers")) || ((bottom === "shorts"))) {
    knee = (hip_y + (((bottom === "trousers")) ? F((leg_len * 45), 100) : F((leg_len * 30), 100)));
    for ([side, lift] of [[(-1), lift_l], [1, lift_r]]) {
      end_y = (((bottom === "trousers")) ? ((GROUND - (foot_h * 2)) - lift) : knee);
      s.push(C((CX + (side * lx)), (hip_y - F(leg_r, 2)), (CX + (side * lx)), end_y, F((leg_r * 12), 10), "cloth_b", 14, "bottom"));
    }
    s.push(R(((CX - lx) - leg_r), (hip_y - leg_r), ((CX + lx) + leg_r), (hip_y + F(leg_r, 2)), F(leg_r, 2), "cloth_b", 14, "bottom"));
  }
  if (["skirt", "kilt"].includes(bottom)) {
    hem = (hip_y + F((leg_len * (((bottom === "skirt")) ? 55 : 35)), 100));
    mat = (((bottom === "skirt")) ? "cloth_b" : "leather");
    s.push(T((CX - F((tw * 45), 100)), (hip_y - leg_r), (CX + F((tw * 45), 100)), (hip_y - leg_r), (CX + F((tw * 62), 100)), hem, mat, 15, "bottom"));
    s.push(T((CX - F((tw * 45), 100)), (hip_y - leg_r), (CX - F((tw * 62), 100)), hem, (CX + F((tw * 62), 100)), hem, mat, 15, "bottom"));
  }
  s.push(R((CX - F(tw, 2)), (sh_y + bob), (CX + F(tw, 2)), (hip_y + leg_r), F((tw * 30), 100), "skin", 20, "torso"));
  ta = "cloth_a";
  if (["tunic", "crop", "wrap", "cloak"].includes(top_kind)) {
    hem = (hip_y + (((top_kind === "tunic")) ? F((leg_len * 30), 100) : (((top_kind === "crop")) ? F((-torso_h), 4) : leg_r)));
    s.push(R((CX - F((tw * 54), 100)), ((sh_y + bob) - px), (CX + F((tw * 54), 100)), hem, F((tw * 28), 100), ta, 22, "top"));
    if ((top_kind === "wrap")) {
      s.push(C((CX - F((tw * 45), 100)), (sh_y + bob), (CX + F((tw * 40), 100)), (hip_y - F(torso_h, 6)), F((tw * 10), 100), "cloth_b", 23, "pattern"));
    }
  } else if ((top_kind === "vest")) {
    s.push(R((CX - F((tw * 54), 100)), ((sh_y + bob) - px), (CX - F((tw * 10), 100)), (hip_y + leg_r), F((tw * 20), 100), ta, 22, "top"));
    s.push(R((CX + F((tw * 10), 100)), ((sh_y + bob) - px), (CX + F((tw * 54), 100)), (hip_y + leg_r), F((tw * 20), 100), ta, 22, "top"));
    s.push(R((CX - F((tw * 12), 100)), (sh_y + bob), (CX + F((tw * 12), 100)), hip_y, F(tw, 20), "cloth_b", 21, "top"));
  } else if (["robe", "dress"].includes(top_kind)) {
    hem = (((top_kind === "robe")) ? (GROUND - foot_h) : (hip_y + F((leg_len * 55), 100)));
    wide = F((tw * (((top_kind === "robe")) ? 70 : 78)), 100);
    s.push(R((CX - F((tw * 54), 100)), ((sh_y + bob) - px), (CX + F((tw * 54), 100)), hip_y, F((tw * 28), 100), ta, 22, "top"));
    s.push(T((CX - F((tw * 50), 100)), (hip_y - F(torso_h, 4)), (CX + F((tw * 50), 100)), (hip_y - F(torso_h, 4)), (CX + wide), hem, ta, 23, "top"));
    s.push(T((CX - F((tw * 50), 100)), (hip_y - F(torso_h, 4)), (CX - wide), hem, (CX + wide), hem, ta, 23, "top"));
    s.push(C(CX, ((sh_y + bob) + F(torso_h, 5)), CX, (hem - px), Math.max(F((tw * 5), 100), 1), "cloth_b", 24, "pattern"));
  } else if ((top_kind === "apron")) {
    s.push(R((CX - F((tw * 54), 100)), ((sh_y + bob) - px), (CX + F((tw * 54), 100)), (hip_y + leg_r), F((tw * 28), 100), "cloth_b", 22, "top"));
    s.push(R((CX - F((tw * 40), 100)), ((sh_y + bob) + F(torso_h, 4)), (CX + F((tw * 40), 100)), (hip_y + F((leg_len * 55), 100)), F(tw, 10), "leather", 25, "top"));
  } else if ((top_kind === "armor_light")) {
    s.push(R((CX - F((tw * 55), 100)), ((sh_y + bob) - px), (CX + F((tw * 55), 100)), (hip_y + leg_r), F((tw * 25), 100), "leather", 22, "top"));
    s.push(C((CX - F((tw * 45), 100)), (sh_y + bob), (CX + F((tw * 45), 100)), (hip_y - F(torso_h, 8)), Math.max(F((tw * 7), 100), 1), "cloth_a", 23, "straps"));
  } else if ((top_kind === "armor_heavy")) {
    s.push(R((CX - F((tw * 58), 100)), ((sh_y + bob) - px), (CX + F((tw * 58), 100)), (hip_y + F((leg_len * 25), 100)), F((tw * 22), 100), "metal", 22, "top"));
    s.push(R((CX - F((tw * 30), 100)), ((sh_y + bob) + F(torso_h, 5)), (CX + F((tw * 30), 100)), (hip_y - F(torso_h, 8)), F(tw, 10), "cloth_a", 23, "pattern"));
  } else if ((top_kind === "fur_mantle")) {
    s.push(R((CX - F((tw * 54), 100)), ((sh_y + bob) - px), (CX + F((tw * 54), 100)), (hip_y + leg_r), F((tw * 28), 100), ta, 22, "top"));
  }
  if (((top_kind === "fur_mantle")) || (("fur" === back))) {
    s.push(E(CX, ((sh_y + bob) + F(torso_h, 10)), F((tw * 68), 100), F((torso_h * 28), 100), "fur", 26, "top"));
  }
  if (["backpack", "big_pack", "quiver"].includes(back)) {
    for (side of [(-1), 1]) {
      s.push(C((CX + F(((side * tw) * 30), 100)), (sh_y + bob), (CX + F(((side * tw) * 26), 100)), (hip_y - F(torso_h, 4)), Math.max(F(px, 2), F(tw, 16)), "leather", 27, "straps", {snap: true}));
    }
  }
  if ((acc.includes("belt")) || (["tunic", "robe", "armor_light", "apron"].includes(top_kind))) {
    s.push(R((CX - F((tw * 55), 100)), (hip_y - F(torso_h, 8)), (CX + F((tw * 55), 100)), ((hip_y - F(torso_h, 8)) + Math.max(F(torso_h, 9), px)), F(px, 2), "leather", 27, "belt", {snap: true}));
    s.push(R((CX - F((tw * 9), 100)), ((hip_y - F(torso_h, 8)) - F(px, 2)), (CX + F((tw * 9), 100)), (((hip_y - F(torso_h, 8)) + Math.max(F(torso_h, 9), px)) + F(px, 2)), F(px, 2), "brass", 28, "buckle"));
  }
  if (acc.includes("pouches")) {
    for (side of [(-1), 1]) {
      s.push(R(((CX + F(((side * tw) * 35), 100)) - F(tw, 10)), (hip_y - F(torso_h, 10)), ((CX + F(((side * tw) * 35), 100)) + F(tw, 10)), (hip_y + F(torso_h, 10)), F(tw, 20), "leather", 29, "pouches"));
    }
  }
  if (acc.includes("necklace")) {
    s.push(A(CX, (sh_y + bob), F((tw * 32), 100), F((torso_h * 30), 100), Math.max(px, F(torso_h, 25)), 1, "brass", 28, "necklace"));
    s.push(E(CX, ((sh_y + bob) + F((torso_h * 30), 100)), F((tw * 6), 100), F((tw * 6), 100), "gem", 29, "necklace"));
  }
  if (acc.includes("scarf")) {
    s.push(R((CX - F((tw * 45), 100)), ((sh_y + bob) - F(head_h, 12)), (CX + F((tw * 45), 100)), ((sh_y + bob) + F(head_h, 12)), F(tw, 10), "cloth_b", 29, "scarf"));
    s.push(C((CX + F((tw * 20), 100)), (sh_y + bob), (CX + F((tw * 30), 100)), ((sh_y + bob) + F((torso_h * 45), 100)), F((tw * 8), 100), "cloth_b", 29, "scarf"));
  }
  if (acc.includes("pauldrons")) {
    for (side of [(-1), 1]) {
      s.push(E((CX + F(((side * tw) * 50), 100)), ((sh_y + bob) + F(head_h, 20)), F((tw * 28), 100), F((tw * 20), 100), "metal", 36, "pauldrons"));
    }
  }
  if (acc.includes("tattoo")) {
    for (i = 0, _e2 = 2; i < _e2; i += 1) {
      y = ((sh_y + bob) + F((torso_h * (30 + (i * 18))), 100));
      s.push(C((CX - F((tw * 42), 100)), y, (CX - F((tw * 20), 100)), (y + px), Math.max(F(px, 2), 1), "arcane", 24, "pattern"));
    }
  }
  arm_r = Math.max(F((tw * 12), 100), F(px, 2));
  swing = (get(pose, "swing", 0) * px);
  hands = ({});
  for (side of [(-1), 1]) {
    [sx, sy] = [(CX + (side * (F(tw, 2) - F(arm_r, 2)))), ((sh_y + bob) + arm_r)];
    hx = (CX + (side * (F(tw, 2) + F((tw * 14), 100))));
    hy = (((hip_y + arm_r) + (side * swing)) + bob);
    s.push(C(sx, sy, hx, hy, arm_r, "skin", 30, "arms"));
    if (["tunic", "robe", "dress", "fur_mantle", "armor_heavy", "cloak", "wrap"].includes(top_kind)) {
      mat = (((top_kind === "armor_heavy")) ? "metal" : ta);
      s.push(C(sx, sy, F((sx + hx), 2), F((sy + hy), 2), F((arm_r * 12), 10), mat, 31, "sleeves"));
    }
    if (acc.includes("bracers")) {
      s.push(C(F((sx + (2 * hx)), 3), F((sy + (2 * hy)), 3), hx, (hy - arm_r), F((arm_r * 11), 10), "leather", 31, "bracers"));
    }
    s.push(E(hx, hy, F((arm_r * 13), 10), F((arm_r * 13), 10), "skin", 33, "hands"));
    hands[side] = [hx, hy];
  }
  if ((get(g, "held_spec", null) !== null)) {
    _held_data(s, g["held_spec"], hands[(-1)], (-1), head_h, px);
  } else {
    _held(s, g["held"], hands[(-1)], (-1), tw, head_h, px);
  }
  if ((get(g, "offhand_spec", null) !== null)) {
    _held_data(s, g["offhand_spec"], hands[1], 1, head_h, px);
  } else {
    _held(s, g["offhand"], hands[1], 1, tw, head_h, px);
  }
  ear_len = Math.min(F((head_w * g["ear_len"]), 100), (496 - F(head_w, 2)));
  ear_w = F((head_h * g["ear_w"]), 100);
  for (side of [(-1), 1]) {
    bx = (CX + F(((side * head_w) * 38), 100));
    tip = [(CX + (side * (F(head_w, 2) + ear_len))), (head_cy - F((head_h * g["ear_lift"]), 100))];
    s.push(T(bx, (head_cy - F((ear_w * 6), 10)), bx, (head_cy + F((ear_w * 4), 10)), tip[0], tip[1], "skin", 40, "ears", {snap: true}));
    s.push(T((bx + F((side * head_w), 20)), (head_cy - F((ear_w * 3), 10)), (bx + F((side * head_w), 20)), (head_cy + F(ear_w, 5)), (CX + (side * (F(head_w, 2) + F((ear_len * 7), 10)))), (tip[1] + F((head_cy - tip[1]), 5)), "skin", 41, "ear_inner", {bias: (-1)}));
    if (acc.includes("earrings")) {
      s.push(A((bx + F((side * ear_len), 3)), (head_cy + F((ear_w * 3), 10)), F(head_w, 14), F(head_w, 14), Math.max(px, F(head_w, 40)), 0, "brass", 42, "earrings"));
    }
    if (acc.includes("fins")) {
      s.push(T((bx + F((side * ear_len), 4)), (head_cy - ear_w), (bx + (side * ear_len)), (head_cy - F((ear_w * 14), 10)), (bx + F(((side * ear_len) * 7), 10)), (head_cy - F(ear_w, 5)), "arcane", 39, "fins"));
    }
  }
  s.push(E(CX, head_cy, F(head_w, 2), F(head_h, 2), "skin", 44, "head"));
  s.push(E(CX, (head_cy + F(head_h, 6)), F((head_w * 40), 100), F((head_h * 40), 100), "skin", 44, "head"));
  _face(s, g, head_cy, head_w, head_h, px, pose, (style_px || px));
  _hair(s, g["hair"], head_cy, head_w, head_h, px);
  _headwear(s, g["headwear"], head_cy, head_w, head_h, px);
  if (acc.includes("glasses")) {
    for (side of [(-1), 1]) {
      s.push(A((CX + F(((side * head_w) * 20), 100)), (head_cy + F((head_h * 4), 100)), F((head_w * 14), 100), F((head_h * 12), 100), Math.max(px, F(head_w, 40)), 0, "brass", 56, "glasses", {snap: true}));
    }
  }
  if ((acc.includes("goggles")) && ((g["headwear"] !== "goggles"))) {
    _goggles(s, (head_cy - F((head_h * 30), 100)), head_w, head_h, px, 57);
  }
  return s;
}

function _goggles(s, y, head_w, head_h, px, z) {
  let side;
  s.push(R((CX - F((head_w * 50), 100)), (y - F(head_h, 22)), (CX + F((head_w * 50), 100)), (y + F(head_h, 22)), F(px, 2), "leather", z, "goggles", {snap: true}));
  for (side of [(-1), 1]) {
    s.push(E((CX + F(((side * head_w) * 20), 100)), y, F((head_w * 14), 100), F((head_h * 11), 100), "brass", (z + 1), "goggles"));
    s.push(E((CX + F(((side * head_w) * 20), 100)), y, F((head_w * 9), 100), F((head_h * 7), 100), "gem", (z + 2), "highlights"));
  }
}

function _face(s, g, cy, hw, hh, px, pose, style_px) {
  let ey, boost, erx, ery, ex_off, expr, blink, side, my, mw, th, ex, wink, tilt, lift, by, inner, outer, r, off;
  ey = (cy + F((hh * 4), 100));
  boost = (100 + get(TIER_EYE, F(D, style_px), 0));
  [erx, ery] = [F((((hw * 10) * g["eye"]) * boost), 1000000), F((((hh * 9) * g["eye"]) * boost), 1000000)];
  ex_off = Math.max(F((hw * 21), 100), (Math.max(erx, F(px, 2)) + px));
  expr = g["expression"];
  blink = get(pose, "blink", 0);
  for (side of [(-1), 1]) {
    ex = (CX + (side * ex_off));
    wink = (((expr === "playful")) && ((side === 1)));
    if (blink || wink) {
      s.push(C((ex - erx), ey, (ex + erx), ey, Math.max(F(px, 2), F(hh, 60)), "mouth", 50, "eyes", {snap: true}));
      continue;
    }
    s.push(E(ex, ey, erx, ery, "iris", 50, "eyes", {snap: true}));
    s.push(E(ex, ey, erx, ery, "eye_white", 51, "eye_whites"));
    s.push(E((ex + F((side * erx), 5)), ey, F((erx * 60), 100), F((ery * 70), 100), "iris", 52, "eye_whites"));
    s.push(E((ex + F((side * erx), 5)), ey, F((erx * 28), 100), F((ery * 36), 100), "mouth", 53, "pupils"));
    s.push(E((ex - F(erx, 3)), (ey - F(ery, 3)), (F(erx, 5) + 1), (F(ery, 5) + 1), "eye_white", 54, "highlights"));
    tilt = get(({["angry"]: 3, ["annoyed"]: 2, ["surprised"]: (-2), ["thoughtful"]: (((side === 1)) ? 1 : 0)}), expr, 0);
    lift = ((((expr === "surprised")) || (((expr === "curious")) && ((side === (-1))))) ? F((hh * 5), 100) : 0);
    by = (((ey - ery) - F((hh * 7), 100)) - lift);
    [inner, outer] = [(ex - F(((side * erx) * 12), 10)), (ex + F(((side * erx) * 12), 10))];
    s.push(C(inner, (by + F((tilt * hh), 60)), outer, by, Math.max(F(px, 2), F(hh, 50)), "hair", 55, "brows"));
  }
  s.push(E(CX, (cy + F((hh * 18), 100)), F(((hw * 9) * g["nose"]), 10000), F(((hh * 15) * g["nose"]), 10000), "skin", 52, "nose", {bias: (-1)}));
  s.push(E((CX - F((hw * 2), 100)), (cy + F((hh * 15), 100)), F(((hw * 4) * g["nose"]), 10000), F(((hh * 7) * g["nose"]), 10000), "skin", 53, "highlights", {bias: 1}));
  [my, mw] = [(cy + F((hh * 33), 100)), F((hw * 22), 100)];
  th = Math.max(px, F(hh, 40));
  if (["happy", "playful"].includes(expr)) {
    s.push(A(CX, (my - F((hh * 6), 100)), mw, F((hh * 10), 100), th, 1, "mouth", 53, "mouth", {snap: true}));
    if ((expr === "playful")) {
      s.push(E((CX + F(mw, 3)), (my + F((hh * 5), 100)), F(mw, 4), F((hh * 5), 100), "mouth", 54, "tongue", {bias: 2}));
    }
  } else if ((expr === "angry")) {
    s.push(A(CX, (my + F((hh * 7), 100)), mw, F((hh * 9), 100), th, (-1), "mouth", 53, "mouth", {snap: true}));
    for (side of [(-1), 1]) {
      s.push(T((CX + F(((side * mw) * 6), 10)), (my - th), (CX + F(((side * mw) * 3), 10)), (my - th), (CX + F(((side * mw) * 45), 100)), (my - F((hh * 9), 100)), "teeth", 54, "tusks"));
    }
  } else if (((expr === "surprised")) || ((expr === "curious"))) {
    r = F((mw * (((expr === "surprised")) ? 45 : 28)), 100);
    s.push(E(CX, my, r, F((r * 12), 10), "mouth", 53, "mouth", {snap: true}));
  } else if ((expr === "confident")) {
    s.push(A((CX + F(mw, 3)), (my - F((hh * 5), 100)), F((mw * 7), 10), F((hh * 8), 100), th, 1, "mouth", 53, "mouth", {snap: true}));
    s.push(T((CX - F((mw * 5), 10)), my, (CX - F((mw * 3), 10)), my, (CX - F((mw * 4), 10)), (my - F((hh * 9), 100)), "teeth", 54, "tusks"));
  } else {
    off = (((expr === "thoughtful")) ? F(mw, 4) : 0);
    s.push(C(((CX - F((mw * 7), 10)) + off), my, ((CX + F((mw * 7), 10)) + off), (my + (((expr === "annoyed")) ? F(hh, 60) : 0)), (F(th, 2) + 1), "mouth", 53, "mouth", {snap: true}));
  }
  if ((g["accessories"].includes("tusks")) && ((expr !== "angry"))) {
    for (side of [(-1), 1]) {
      s.push(T((CX + F(((side * mw) * 6), 10)), (my + th), (CX + F(((side * mw) * 3), 10)), (my + th), (CX + F(((side * mw) * 45), 100)), (my - F((hh * 8), 100)), "teeth", 54, "tusks"));
    }
  }
  if (g["accessories"].includes("beard")) {
    s.push(T((CX - F((hw * 34), 100)), (cy + F((hh * 26), 100)), (CX + F((hw * 34), 100)), (cy + F((hh * 26), 100)), CX, (cy + F((hh * 95), 100)), "hair", 56, "beard"));
    s.push(E(CX, (cy + F((hh * 45), 100)), F((hw * 32), 100), F((hh * 22), 100), "hair", 56, "beard"));
    s.push(C((CX - F((hw * 25), 100)), (cy + F((hh * 28), 100)), (CX + F((hw * 25), 100)), (cy + F((hh * 28), 100)), F(hh, 18), "hair", 57, "beard"));
  }
}

function _hair(s, style, cy, hw, hh, px) {
  let top, i, side, _e3;
  top = (cy - F(hh, 2));
  if ((style === "none")) {
    return;
  }
  if (["short", "wild", "braids", "twintails", "long", "ponytail", "bun", "topknot"].includes(style)) {
    s.push(A(CX, (cy - F(hh, 10)), F((hw * 51), 100), F((hh * 44), 100), F((hh * 16), 100), (-1), "hair", 58, "hair"));
  }
  if ((style === "topknot")) {
    s.push(E(CX, (top - F(hh, 10)), F((hw * 16), 100), F((hh * 16), 100), "hair", 58, "hair", {snap: true}));
  }
  if ((style === "bun")) {
    s.push(E(CX, (top + F(hh, 20)), F((hw * 22), 100), F((hh * 18), 100), "hair", 57, "hair"));
  }
  if ((style === "mohawk")) {
    s.push(E(CX, (top + F(hh, 20)), F((hw * 10), 100), F((hh * 30), 100), "hair", 58, "hair", {snap: true}));
  }
  if ((style === "wild")) {
    for (i = (-2), _e3 = 3; i < _e3; i += 1) {
      s.push(T(((CX + F(((i * hw) * 18), 100)) - F(hw, 10)), (top + F(hh, 6)), ((CX + F(((i * hw) * 18), 100)) + F(hw, 10)), (top + F(hh, 6)), (CX + F(((i * hw) * 24), 100)), ((top - F(hh, 6)) - F((Math.abs(i) * hh), 30)), "hair", 59, "hair"));
    }
  }
  if (((style === "braids")) || ((style === "twintails"))) {
    for (side of [(-1), 1]) {
      if ((style === "braids")) {
        s.push(C((CX + F(((side * hw) * 45), 100)), cy, (CX + F(((side * hw) * 50), 100)), (cy + F((hh * 70), 100)), F((hw * 8), 100), "hair", 59, "hair", {snap: true}));
      } else {
        s.push(E((CX + F(((side * hw) * 55), 100)), (cy - F((hh * 10), 100)), F((hw * 16), 100), F((hh * 30), 100), "hair", 43, "hair"));
      }
    }
  }
}

function _headwear(s, kind, cy, hw, hh, px) {
  let top, z, i, side, _e4, _e5;
  top = (cy - F(hh, 2));
  z = 60;
  if ((kind === "hood")) {
    s.push(A(CX, (cy + F(hh, 10)), F((hw * 58), 100), F((hh * 62), 100), F((hh * 20), 100), (-1), "cloth_a", z, "headwear.large"));
    s.push(T((CX - F(hw, 5)), (top - F(hh, 20)), (CX + F(hw, 5)), (top - F(hh, 20)), (CX + F(hw, 4)), (top - F((hh * 30), 100)), "cloth_a", z, "headwear"));
  } else if ((kind === "bandana")) {
    s.push(R((CX - F((hw * 50), 100)), (cy - F((hh * 22), 100)), (CX + F((hw * 50), 100)), (cy - F((hh * 12), 100)), F(px, 2), "cloth_b", z, "headwear", {snap: true}));
    s.push(T((CX + F((hw * 45), 100)), (cy - F((hh * 18), 100)), (CX + F((hw * 70), 100)), (cy - F((hh * 5), 100)), (CX + F((hw * 62), 100)), (cy - F((hh * 30), 100)), "cloth_b", z, "headwear"));
  } else if ((kind === "goggles")) {
    _goggles(s, (cy - F((hh * 30), 100)), hw, hh, px, z);
  } else if ((kind === "helm")) {
    s.push(A(CX, (cy - F(hh, 20)), F((hw * 54), 100), F((hh * 50), 100), F((hh * 24), 100), (-1), "metal", z, "headwear.large"));
    s.push(R((CX - F(hw, 25)), (cy - F(hh, 5)), (CX + F(hw, 25)), (cy + F((hh * 12), 100)), F(px, 2), "metal", (z + 1), "headwear", {snap: true}));
  } else if ((kind === "feather_crown")) {
    s.push(R((CX - F((hw * 46), 100)), (cy - F((hh * 34), 100)), (CX + F((hw * 46), 100)), (cy - F((hh * 24), 100)), F(px, 2), "brass", z, "headwear", {snap: true}));
    for (i = (-2), _e4 = 3; i < _e4; i += 1) {
      s.push(C((CX + F(((i * hw) * 17), 100)), (cy - F((hh * 34), 100)), (CX + F(((i * hw) * 26), 100)), ((top - F((hh * 42), 100)) + F((Math.abs(i) * hh), 10)), F((hw * 5), 100), (MOD(i, 2) ? "cloth_a" : "fur"), (z - 1), "headwear.large", {snap: true}));
    }
  } else if ((kind === "chef_hat")) {
    s.push(E(CX, (top - F(hh, 8)), F((hw * 40), 100), F((hh * 30), 100), "paper", z, "headwear.large"));
    s.push(R((CX - F((hw * 36), 100)), (top - F(hh, 20)), (CX + F((hw * 36), 100)), (top + F(hh, 10)), F(hw, 20), "paper", (z + 1), "headwear"));
  } else if ((kind === "horns")) {
    for (side of [(-1), 1]) {
      s.push(C((CX + F(((side * hw) * 25), 100)), (top + F(hh, 8)), (CX + F(((side * hw) * 55), 100)), (top - F((hh * 25), 100)), F((hw * 7), 100), "fur", z, "headwear.large", {snap: true}));
      s.push(C((CX + F(((side * hw) * 55), 100)), (top - F((hh * 25), 100)), (CX + F(((side * hw) * 45), 100)), (top - F((hh * 45), 100)), F((hw * 5), 100), "fur", z, "headwear.large", {snap: true}));
    }
    s.push(R((CX - F((hw * 46), 100)), (cy - F((hh * 34), 100)), (CX + F((hw * 46), 100)), (cy - F((hh * 24), 100)), F(px, 2), "leather", (z + 1), "headwear", {snap: true}));
  } else if ((kind === "flower_crown")) {
    s.push(A(CX, (cy - F(hh, 10)), F((hw * 50), 100), F((hh * 32), 100), Math.max(px, F(hh, 20)), (-1), "wood", z, "headwear", {snap: true}));
    for (i = (-2), _e5 = 3; i < _e5; i += 1) {
      s.push(E((CX + F(((i * hw) * 20), 100)), ((cy - F((hh * 35), 100)) - F(((2 - Math.abs(i)) * hh), 40)), F((hw * 6), 100), F((hw * 6), 100), (MOD(i, 2) ? "cloth_a" : "glow"), (z + 1), "flowers"));
    }
  } else if ((kind === "headscarf")) {
    s.push(A(CX, cy, F((hw * 54), 100), F((hh * 55), 100), F((hh * 20), 100), (-1), "cloth_b", z, "headwear.large"));
    s.push(T((CX + F((hw * 40), 100)), (cy - F(hh, 10)), (CX + F((hw * 62), 100)), (cy + F((hh * 30), 100)), (CX + F((hw * 30), 100)), (cy + F((hh * 25), 100)), "cloth_b", z, "headwear"));
  } else if ((kind === "cap")) {
    s.push(A(CX, (cy - F(hh, 12)), F((hw * 50), 100), F((hh * 44), 100), F((hh * 22), 100), (-1), "cloth_b", z, "headwear.large"));
  } else if ((kind === "circlet")) {
    s.push(R((CX - F((hw * 48), 100)), (cy - F((hh * 26), 100)), (CX + F((hw * 48), 100)), (cy - F((hh * 20), 100)), F(px, 2), "brass", z, "headwear", {snap: true}));
    s.push(E(CX, (cy - F((hh * 23), 100)), F((hw * 6), 100), F((hw * 6), 100), "gem", (z + 1), "headwear"));
  }
}

function _held(s, kind, hand, side, tw, hh, px) {
  let hx, hy, z, L, i, n, tipm, sd, _e6;
  [hx, hy] = hand;
  z = 34;
  if ((kind === "none")) {
    return;
  }
  L = F((hh * 13), 10);
  if ((kind === "hammer")) {
    s.push(C(hx, (hy + F(L, 5)), (hx + F((side * L), 8)), (hy - F((L * 70), 100)), F(L, 16), "wood", z, "held.large", {snap: true}));
    s.push(R(((hx + F((side * L), 8)) - F(L, 5)), (hy - F((L * 85), 100)), ((hx + F((side * L), 8)) + F(L, 5)), (hy - F((L * 62), 100)), F(L, 30), "metal", (z + 1), "held.large"));
  } else if (["staff", "spear"].includes(kind)) {
    s.push(C(hx, (hy + F((L * 60), 100)), hx, (hy - F((L * 150), 100)), F(L, 18), "wood", z, "held.large", {snap: true}));
    if ((kind === "staff")) {
      s.push(E(hx, (hy - F((L * 158), 100)), F(L, 7), F(L, 7), "arcane", (z + 1), "held.large"));
      s.push(E((hx - F(L, 30)), (hy - F((L * 164), 100)), F(L, 20), F(L, 20), "glow", (z + 2), "highlights"));
    } else {
      s.push(T((hx - F(L, 10)), (hy - F((L * 145), 100)), (hx + F(L, 10)), (hy - F((L * 145), 100)), hx, (hy - F((L * 185), 100)), "metal", (z + 1), "held.large", {snap: true}));
    }
  } else if ((kind === "book")) {
    s.push(R(((hx - F(((side * L) * 5), 100)) - F(L, 4)), (hy - F(L, 3)), ((hx - F(((side * L) * 5), 100)) + F(L, 4)), (hy + F(L, 20)), F(L, 30), "leather", (z + 1), "held"));
    s.push(R(((hx - F(((side * L) * 5), 100)) - F(L, 5)), (hy - F((L * 29), 100)), ((hx - F(((side * L) * 5), 100)) + F(L, 5)), (hy + F(L, 60)), F(L, 60), "paper", (z + 2), "pattern"));
  } else if ((kind === "bow")) {
    s.push(A((hx - F((side * L), 8)), (hy - F(L, 4)), F(L, 3), F((L * 75), 100), Math.max(px, F(L, 18)), 0, "wood", z, "held.large", {snap: true}));
    s.push(R((((hx - F((side * L), 8)) - F(L, 3)) - F(L, 60)), (hy - L), (((hx - F((side * L), 8)) - F(L, 3)) + F(L, 60)), (hy + F(L, 2)), 0, "paper", (z - 1), "held"));
  } else if ((kind === "basket")) {
    s.push(E(hx, (hy + F(L, 10)), F((L * 35), 100), F((L * 25), 100), "wood", (z + 1), "held"));
    s.push(R((hx - F((L * 35), 100)), (hy - F(L, 20)), (hx + F((L * 35), 100)), (hy + F(L, 10)), F(L, 20), "wood", (z + 1), "held"));
    for (i = (-1), _e6 = 2; i < _e6; i += 1) {
      s.push(E((hx + F((i * L), 7)), (hy - F(L, 12)), F(L, 12), F(L, 12), (i ? "cloth_a" : "glow"), (z + 2), "flowers"));
    }
  } else if (["dagger", "sword"].includes(kind)) {
    n = (((kind === "dagger")) ? 60 : 120);
    s.push(T((hx - F(L, 18)), (hy - F(L, 12)), (hx + F(L, 18)), (hy - F(L, 12)), (hx + F((side * L), 20)), (hy - F((L * n), 100)), "metal", (z + 1), (((kind === "sword")) ? "held.large" : "held"), {snap: true}));
    s.push(R((hx - F(L, 7)), (hy - F(L, 12)), (hx + F(L, 7)), (hy - F(L, 20)), F(px, 2), "brass", (z + 2), "held"));
  } else if ((kind === "axe")) {
    s.push(C(hx, (hy + F(L, 5)), hx, (hy - F((L * 90), 100)), F(L, 16), "wood", z, "held.large", {snap: true}));
    s.push(T(hx, (hy - F((L * 95), 100)), hx, (hy - F((L * 55), 100)), (hx + F(((side * L) * 35), 100)), (hy - F((L * 75), 100)), "metal", (z + 1), "held.large"));
  } else if ((kind === "lute")) {
    s.push(C(hx, hy, (hx + F(((side * L) * 50), 100)), (hy - F((L * 70), 100)), F(L, 16), "wood", z, "held"));
    s.push(E((hx - F((side * L), 10)), (hy + F(L, 10)), F((L * 28), 100), F((L * 32), 100), "wood", (z + 1), "held.large"));
    s.push(E((hx - F((side * L), 10)), (hy + F(L, 20)), F(L, 12), F(L, 12), "leather", (z + 2), "pattern"));
  } else if ((kind === "lantern")) {
    s.push(C(hx, hy, hx, (hy + F(L, 5)), (F(L, 40) + 1), "metal", z, "held"));
    s.push(R((hx - F(L, 7)), (hy + F(L, 5)), (hx + F(L, 7)), (hy + F(L, 2)), F(L, 20), "brass", (z + 1), "held"));
    s.push(E(hx, (hy + F((L * 35), 100)), F(L, 12), F(L, 10), "glow", (z + 2), "held"));
  } else if (["ladle", "brush", "wrench", "whip"].includes(kind)) {
    s.push(C(hx, (hy + F(L, 6)), (hx + F((side * L), 5)), (hy - F((L * 65), 100)), F(L, 22), (((kind !== "wrench")) ? "wood" : "metal"), z, "held", {snap: true}));
    tipm = ({["ladle"]: "metal", ["brush"]: "cloth_a", ["wrench"]: "metal", ["whip"]: "leather"})[kind];
    s.push(E((hx + F((side * L), 5)), (hy - F((L * 70), 100)), F(L, 8), F(L, 10), tipm, (z + 1), "held"));
  } else if ((kind === "mug")) {
    s.push(R((hx - F(L, 7)), (hy - F(L, 5)), (hx + F(L, 7)), (hy + F(L, 8)), F(L, 25), "wood", (z + 1), "held"));
    s.push(E(hx, (hy - F(L, 5)), F(L, 7), F(L, 16), "paper", (z + 2), "held"));
  } else if ((kind === "teddy")) {
    s.push(E(hx, (hy + F(L, 12)), F(L, 6), F(L, 5), "fur", (z + 1), "held"));
    s.push(E(hx, (hy - F(L, 6)), F(L, 7), F(L, 8), "fur", (z + 1), "held"));
    for (sd of [(-1), 1]) {
      s.push(E((hx + F((sd * L), 10)), (hy - F(L, 4)), F(L, 20), F(L, 20), "fur", (z + 1), "held"));
    }
  } else if (["scroll", "map"].includes(kind)) {
    s.push(R((hx - F(L, 4)), (hy - F(L, 6)), (hx + F(L, 4)), (hy + F(L, 20)), F(L, 40), "paper", (z + 1), "held"));
    s.push(C((hx - F(L, 4)), (hy - F(L, 6)), (hx - F(L, 4)), (hy + F(L, 20)), F(L, 25), "wood", (z + 2), "held"));
  } else if ((kind === "orb")) {
    s.push(E(hx, (hy - F(L, 6)), F(L, 6), F(L, 6), "arcane", (z + 1), "held.large"));
    s.push(E((hx - F(L, 20)), (hy - F(L, 5)), F(L, 18), F(L, 18), "glow", (z + 2), "highlights"));
  } else if ((kind === "bag")) {
    s.push(E(hx, (hy + F(L, 8)), F(L, 5), F(L, 5), "leather", (z + 1), "held"));
  } else if ((kind === "flask")) {
    s.push(E(hx, hy, F(L, 8), F(L, 7), "gem", (z + 1), "held"));
    s.push(R((hx - F(L, 30)), (hy - F(L, 4)), (hx + F(L, 30)), (hy - F(L, 9)), 0, "paper", (z + 1), "held", {snap: true}));
  } else if ((kind === "shield")) {
    s.push(E((hx - F((side * L), 12)), (hy - F(L, 6)), F((L * 36), 100), F((L * 42), 100), "wood", (z + 1), "held.large"));
    s.push(A((hx - F((side * L), 12)), (hy - F(L, 6)), F((L * 36), 100), F((L * 42), 100), Math.max(px, F(L, 20)), 0, "metal", (z + 2), "held"));
    s.push(E((hx - F((side * L), 12)), (hy - F(L, 6)), F(L, 12), F(L, 12), "brass", (z + 3), "held"));
  }
}

function _held_data(s, spec, hand, side, hh, px) {
  let hx, hy, L, sh, k, a, z, mat, feat, snap;
  [hx, hy] = hand;
  L = F((hh * 13), 10);
  for (sh of spec) {
    k = sh["shape"];
    a = sh["at"];
    z = (34 + get(sh, "layer", 0));
    mat = sh["mat"];
    feat = get(sh, "feat", "held");
    snap = get(sh, "snap", false);
    if ((k === "E")) {
      s.push(E((hx + F(((side * a[0]) * L), 100)), (hy + F((a[1] * L), 100)), F((a[2] * L), 100), F((a[3] * L), 100), mat, z, feat, {snap: snap}));
    } else if ((k === "R")) {
      s.push(R((hx + F(((side * a[0]) * L), 100)), (hy + F((a[1] * L), 100)), (hx + F(((side * a[2]) * L), 100)), (hy + F((a[3] * L), 100)), F((a[4] * L), 100), mat, z, feat, {snap: snap}));
    } else if ((k === "C")) {
      s.push(C((hx + F(((side * a[0]) * L), 100)), (hy + F((a[1] * L), 100)), (hx + F(((side * a[2]) * L), 100)), (hy + F((a[3] * L), 100)), Math.max(1, F((a[4] * L), 100)), mat, z, feat, {snap: snap}));
    } else if ((k === "T")) {
      s.push(T((hx + F(((side * a[0]) * L), 100)), (hy + F((a[1] * L), 100)), (hx + F(((side * a[2]) * L), 100)), (hy + F((a[3] * L), 100)), (hx + F(((side * a[4]) * L), 100)), (hy + F((a[5] * L), 100)), mat, z, feat, {snap: snap}));
    } else if ((k === "A")) {
      s.push(A((hx + F(((side * a[0]) * L), 100)), (hy + F((a[1] * L), 100)), F((a[2] * L), 100), F((a[3] * L), 100), Math.max(px, F((a[4] * L), 100)), a[5], mat, z, feat, {snap: snap}));
    }
  }
}

function signature(data, g) {
  let sig;
  sig = get(get(data, "role", ({})), "signature");
  if (sig) {
    return sig;
  }
  if ((g["held"] !== "none")) {
    return "held";
  }
  if ((g["headwear"] !== "none")) {
    return "headwear";
  }
  if ((g["back"] !== "none")) {
    return "back";
  }
  if (g["accessories"].includes("beard")) {
    return "beard";
  }
  return "top";
}

function shade_index(light, n, bands, dither, x, y, bias) {
  let mid, idx, t16, t, lo;
  mid = F((n - 1), 2);
  if ((bands === 1)) {
    idx = mid;
  } else {
    t16 = F((((light + 1024) * bands) * 16), 2049);
    t = (dither ? F((t16 + F((BAYER4[MOD(y, 4)][MOD(x, 4)] - 8), 2)), 16) : F(t16, 16));
    t = Math.max(0, Math.min((bands - 1), t));
    lo = (((n >= bands)) ? Math.max(0, Math.min((n - bands), (mid - F((bands - 1), 2)))) : 0);
    idx = Math.min((n - 1), (lo + t));
  }
  return Math.max(0, Math.min((n - 1), (idx + bias)));
}

function zoom_plan(from_tier, to_tier, steps) {
  let doublings, t, plan, k, e, size, a, b, w, _e7;
  doublings = 0;
  t = from_tier;
  while ((t < to_tier)) {
    t *= 2;
    doublings += 1;
  }
  plan = [];
  for (k = 0, _e7 = steps; k < _e7; k += 1) {
    e = F(((k * doublings) * 16), Math.max(1, (steps - 1)));
    size = F(((from_tier * (1 * Math.pow(2, F(e, 16)))) * POW2_16[MOD(e, 16)]), 4096);
    size = Math.min(to_tier, Math.max(from_tier, size));
    a = from_tier;
    while ((((a * 2) <= size)) && (((a * 2) <= to_tier))) {
      a *= 2;
    }
    b = Math.min(to_tier, (a * 2));
    w = ((((a === size)) && ((b === a))) ? 16 : F(((size - a) * 16), a));
    if ((b === a)) {
      w = 0;
    }
    plan.push([size, a, b, Math.min(16, w)]);
  }
  return plan;
}

// ---- from pixelgoblin/gen/rig3d.py
const ZC = 512;
const SIN90 = [0, 71, 143, 214, 286, 357, 428, 499, 570, 641, 711, 782, 852, 921, 991, 1060, 1129, 1198, 1266, 1334, 1401, 1468, 1534, 1600, 1666, 1731, 1796, 1860, 1923, 1986, 2048, 2110, 2171, 2231, 2290, 2349, 2408, 2465, 2522, 2578, 2633, 2687, 2741, 2793, 2845, 2896, 2946, 2996, 3044, 3091, 3138, 3183, 3228, 3271, 3314, 3355, 3396, 3435, 3474, 3511, 3547, 3582, 3617, 3650, 3681, 3712, 3742, 3770, 3798, 3824, 3849, 3873, 3896, 3917, 3937, 3956, 3974, 3991, 4006, 4021, 4034, 4046, 4056, 4065, 4074, 4080, 4086, 4090, 4094, 4095, 4096];
const DECAL_FEATS = ["eyes", "eye_whites", "pupils", "highlights", "brows", "mouth", "tongue", "tusks", "pattern", "stitches", "straps", "buckle", "necklace", "ear_inner"];
const WRAP_FEATS = ["top", "bottom", "sleeves", "bracers", "belt", "scarf", "pauldrons", "pouches"];
const HEADWEAR_FEATS = ["headwear", "headwear.large", "goggles", "glasses"];
const HELD_DEPTH = ({["shield"]: 14, ["lute"]: 40, ["bow"]: 8, ["book"]: 55, ["scroll"]: 30, ["map"]: 30});
function isin(deg) {
  let d;
  d = MOD(deg, 360);
  if ((d <= 90)) {
    return SIN90[d];
  }
  if ((d <= 180)) {
    return SIN90[(180 - d)];
  }
  if ((d <= 270)) {
    return (-SIN90[(d - 180)]);
  }
  return (-SIN90[(360 - d)]);
}

function icos(deg) {
  return isin((deg + 90));
}

function _solid(kind, a, sh, i, a2) {
  return ({["k"]: kind, ["a"]: a, ["mat"]: sh.mat, ["feat"]: sh.feat, ["layer"]: sh.z, ["idx"]: i, ["bias"]: sh.bias, ["k2"]: sh.kind, ["a2"]: a2, ["box"]: [0, 0, 0, 0, 0, 0], ["group"]: 0});
}

function _box3(so) {
  let k, a, b, sweep, r;
  k = so["k"];
  a = so["a"];
  if (((k === "ell")) || ((k === "dome"))) {
    return [(a[0] - a[3]), (a[1] - a[4]), (a[2] - a[5]), (a[0] + a[3]), (a[1] + a[4]), (a[2] + a[5])];
  }
  if ((k === "cap")) {
    r = a[6];
    return [(Math.min(a[0], a[3]) - r), (Math.min(a[1], a[4]) - r), (Math.min(a[2], a[5]) - r), (Math.max(a[0], a[3]) + r), (Math.max(a[1], a[4]) + r), (Math.max(a[2], a[5]) + r)];
  }
  if ((k === "pill")) {
    return [a[0], a[1], (a[7] - a[8]), a[2], a[3], (a[7] + (a[9] ? 0 : a[8]))];
  }
  if ((k === "wrap")) {
    b = _bbox(so["k2"], so["a2"]);
    return [b[0], b[1], (a[2] - a[3]), b[2], b[3], (a[2] + (a[4] ? 0 : a[3]))];
  }
  b = _bbox(so["k2"], so["a2"]);
  sweep = 0;
  if ((a.length > 2)) {
    sweep = F((Math.max(0, (Math.max(Math.abs((b[0] - a[2])), Math.abs((b[2] - a[2]))) - a[3])) * a[4]), 100);
  }
  return [b[0], b[1], a[0], b[2], b[3], (a[1] + sweep)];
}

function _profile(off, half, depth) {
  let u, q;
  if ((half <= 0)) {
    return 0;
  }
  u = F((off * 4096), half);
  q = ((4096 * 4096) - (u * u));
  if ((q < 0)) {
    return (-1);
  }
  return F((depth * isqrt(q)), 4096);
}

function _column(so, x, y) {
  let k, a, u, v, q, e, cx, cy, cz, rx, ry, rz, th, drop, eo, irx, iry, irz, ei, out, sw, u2, v2, q2;
  k = so["k"];
  a = so["a"];
  if ((k === "ell")) {
    u = F(((x - a[0]) * 4096), Math.max(1, a[3]));
    v = F(((y - a[1]) * 4096), Math.max(1, a[4]));
    q = (((4096 * 4096) - (u * u)) - (v * v));
    if ((q < 0)) {
      return [];
    }
    e = F((a[5] * isqrt(q)), 4096);
    return [(a[2] - e), (a[2] + e)];
  }
  if ((k === "pill")) {
    if (!_inside("R", [a[0], a[1], a[2], a[3], a[4]], x, y)) {
      return [];
    }
    e = _profile((x - a[5]), a[6], a[8]);
    if ((e < 0)) {
      return [];
    }
    return [(a[7] - e), (a[9] ? a[7] : (a[7] + e))];
  }
  if ((k === "wrap")) {
    if (!_inside(so["k2"], so["a2"], x, y)) {
      return [];
    }
    e = _profile((x - a[0]), a[1], a[3]);
    if ((e < 0)) {
      return [];
    }
    return [(a[2] - e), (a[4] ? a[2] : (a[2] + e))];
  }
  if ((k === "slab")) {
    if (!_inside(so["k2"], so["a2"], x, y)) {
      return [];
    }
    if ((a.length > 2)) {
      sw = F((Math.max(0, (Math.abs((x - a[2])) - a[3])) * a[4]), 100);
      return [(a[0] + sw), (a[1] + sw)];
    }
    return [a[0], a[1]];
  }
  if ((k === "dome")) {
    [cx, cy, cz, rx, ry, rz, th, drop] = [a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7]];
    if ((y > (cy + drop))) {
      return [];
    }
    u = F(((x - cx) * 4096), Math.max(1, rx));
    v = F(((y - cy) * 4096), Math.max(1, ry));
    q = (((4096 * 4096) - (u * u)) - (v * v));
    if ((q < 0)) {
      return [];
    }
    eo = F((rz * isqrt(q)), 4096);
    [irx, iry, irz] = [(rx - th), (ry - th), (rz - th)];
    ei = (-1);
    if (((irx > 0)) && ((iry > 0)) && ((irz > 0))) {
      u2 = F(((x - cx) * 4096), irx);
      v2 = F(((y - cy) * 4096), iry);
      q2 = (((4096 * 4096) - (u2 * u2)) - (v2 * v2));
      if ((q2 >= 0)) {
        ei = F((irz * isqrt(q2)), 4096);
      }
    }
    out = [];
    if ((ei < 0)) {
      out.push(cz);
    } else {
      out.push(((cz + ei) + 1));
    }
    out.push((cz + eo));
    if (((y <= cy)) && ((ei < 0))) {
      out.push((cz - eo));
      out.push((cz - 1));
    }
    return out;
  }
  return [];
}

function _in_cap(a, x, y, z) {
  let x0, y0, z0, x1, y1, z1, r, dx, dy, dz, px, py, pz, len2, dot, qx, qy, qz;
  [x0, y0, z0, x1, y1, z1, r] = [a[0], a[1], a[2], a[3], a[4], a[5], a[6]];
  [dx, dy, dz] = [(x1 - x0), (y1 - y0), (z1 - z0)];
  [px, py, pz] = [(x - x0), (y - y0), (z - z0)];
  len2 = (((dx * dx) + (dy * dy)) + (dz * dz));
  dot = (((px * dx) + (py * dy)) + (pz * dz));
  if (((len2 === 0)) || ((dot <= 0))) {
    return (((((px * px) + (py * py)) + (pz * pz)) <= (r * r)));
  }
  if ((dot >= len2)) {
    [qx, qy, qz] = [(x - x1), (y - y1), (z - z1)];
    return (((((qx * qx) + (qy * qy)) + (qz * qz)) <= (r * r)));
  }
  return (((((((px * px) + (py * py)) + (pz * pz)) * len2) - (dot * dot)) <= ((r * r) * len2)));
}

function front_z(so, x, y, fallback) {
  let c, best, i, b, z;
  if ((so["k"] === "cap")) {
    b = so["box"];
    z = b[2];
    while ((z <= b[5])) {
      if (_in_cap(so["a"], x, y, z)) {
        return z;
      }
      z += 4;
    }
    return fallback;
  }
  c = _column(so, x, y);
  if ((c.length === 0)) {
    return fallback;
  }
  best = c[0];
  i = 0;
  while ((i < c.length)) {
    if ((c[i] < best)) {
      best = c[i];
    }
    i += 2;
  }
  return best;
}

function _host(solids, x, y, below) {
  let best, j, so, _e8;
  best = (-1);
  for (j = 0, _e8 = solids.length; j < _e8; j += 1) {
    so = solids[j];
    if (((so["layer"] < below)) && _inside(so["k2"], so["a2"], x, y)) {
      if (((best < 0)) || ((so["layer"] > solids[best]["layer"])) || (((so["layer"] === solids[best]["layer"])) && ((so["idx"] > solids[best]["idx"])))) {
        best = j;
      }
    }
  }
  return best;
}

function lift(shapes, g, px, pose) {
  let half, head, torso, i, ha, hcx, hcy, hrx, hry, hrz, ta, tw, tcx, thw, tdz, stride, arm_z, HZ, back0, solids, decals, fronts, n, order, sh, a, f, k, b, cx, cy, w, h, side, leg_dz, arm_dz, so, j, zs, rz, z0, z1, t, hz, dz, front, phw, hw, drop, kind, pct, depth, _e9, _e10, _e11, _e12;
  half = F(px, 2);
  head = (-1);
  torso = (-1);
  for (i = 0, _e9 = shapes.length; i < _e9; i += 1) {
    if (((shapes[i].feat === "head")) && ((head < 0))) {
      head = i;
    }
    if (((shapes[i].feat === "torso")) && ((torso < 0))) {
      torso = i;
    }
  }
  ha = (((head >= 0)) ? _snap(shapes[head], half) : [CX, 300, 200, 200]);
  [hcx, hcy, hrx, hry] = [ha[0], ha[1], ha[2], ha[3]];
  hrz = F((hrx * 88), 100);
  ta = (((torso >= 0)) ? _snap(shapes[torso], half) : [(CX - 120), 400, (CX + 120), 700, 40]);
  tw = (ta[2] - ta[0]);
  tcx = F((ta[0] + ta[2]), 2);
  thw = F(tw, 2);
  tdz = F((tw * 38), 100);
  stride = ((get(pose, "stride", 0) * px) * 3);
  arm_z = (ZC - F((tdz * 50), 100));
  HZ = (ZC - F((tdz * 55), 100));
  back0 = (ZC + tdz);
  solids = [];
  decals = [];
  fronts = [];
  for (i = 0, _e10 = shapes.length; i < _e10; i += 1) {
    sh = shapes[i];
    a = _snap(sh, half);
    f = sh.feat;
    k = sh.kind;
    b = _bbox(k, a);
    cx = F((b[0] + b[2]), 2);
    cy = F((b[1] + b[3]), 2);
    w = (b[2] - b[0]);
    h = (b[3] - b[1]);
    side = (((cx < CX)) ? (-1) : 1);
    leg_dz = (stride * side);
    arm_dz = ((-stride) * side);
    so = null;
    if (DECAL_FEATS.includes(f)) {
      decals.push(({["k2"]: k, ["a2"]: a, ["mat"]: sh.mat, ["feat"]: f, ["layer"]: sh.z, ["idx"]: i, ["bias"]: sh.bias, ["cx"]: cx, ["cy"]: cy, ["group"]: 0}));
      continue;
    }
    if ((f === "head")) {
      if ((i === head)) {
        so = _solid("ell", [a[0], a[1], HZ, a[2], a[3], Math.max(half, F((a[2] * 88), 100))], sh, i, a);
      } else {
        so = _solid("ell", [a[0], a[1], (HZ - F((a[2] * 10), 100)), a[2], a[3], Math.max(half, F((a[2] * 88), 100))], sh, i, a);
      }
    } else if ((f === "torso")) {
      so = _solid("pill", [a[0], a[1], a[2], a[3], a[4], cx, Math.max(1, F(w, 2)), ZC, Math.max(half, tdz), 0], sh, i, a);
    } else if (((f === "legs")) || (((f === "bottom")) && ((k === "C")))) {
      [z0, z1] = [ZC, (ZC + leg_dz)];
      if ((a[1] > a[3])) {
        [z0, z1] = [z1, z0];
      }
      so = _solid("cap", [a[0], a[1], z0, a[2], a[3], z1, Math.max(half, a[4])], sh, i, a);
    } else if ((f === "feet")) {
      so = _solid("ell", [a[0], a[1], ((ZC - F((a[2] * 40), 100)) + leg_dz), a[2], a[3], Math.max(half, F((a[2] * 140), 100))], sh, i, a);
    } else if (((f === "arms")) || ((f === "sleeves")) || ((f === "bracers"))) {
      [z0, z1] = [arm_z, (arm_z + arm_dz)];
      if ((a[1] > a[3])) {
        [z0, z1] = [z1, z0];
      }
      if ((k === "C")) {
        so = _solid("cap", [a[0], a[1], z0, a[2], a[3], z1, Math.max(half, a[4])], sh, i, a);
      }
    } else if ((f === "hands")) {
      so = _solid("ell", [a[0], a[1], (arm_z + arm_dz), a[2], a[3], Math.max(half, a[2])], sh, i, a);
    } else if (((f === "ears")) || ((f === "fins")) || ((f === "earrings"))) {
      t = Math.max(half, F((hrx * 10), 100));
      hz = (HZ + F((hrz * 15), 100));
      if ((f === "fins")) {
        so = _solid("slab", [hz, (hz + (2 * t)), hcx, hrx, 45], sh, i, a);
      } else if ((f === "earrings")) {
        so = _solid("slab", [((hz - t) - half), ((hz + t) + half), hcx, hrx, 45], sh, i, a);
      } else {
        so = _solid("slab", [(hz - t), (hz + t), hcx, hrx, 45], sh, i, a);
      }
    } else if (WRAP_FEATS.includes(f)) {
      if ((f === "pouches")) {
        so = _solid("pill", [a[0], a[1], a[2], a[3], a[4], cx, Math.max(1, F(w, 2)), (ZC - F((tdz * 60), 100)), Math.max(half, F(w, 2)), 0], sh, i, a);
      } else if (((f === "scarf")) && ((k === "C"))) {
        so = _solid("cap", [a[0], a[1], (ZC - F((tdz * 105), 100)), a[2], a[3], (ZC - F((tdz * 105), 100)), Math.max(half, a[4])], sh, i, a);
      } else if ((k === "R")) {
        dz = Math.max(half, F((tdz * (104 + (2 * Math.max(0, (sh.z - 20))))), 100));
        front = ((((w < F((tw * 85), 100))) && ((Math.abs((cx - tcx)) < F(w, 4)))) ? 1 : 0);
        phw = Math.max(thw, Math.max(Math.abs((a[0] - tcx)), Math.abs((a[2] - tcx))));
        so = _solid("pill", [a[0], a[1], a[2], a[3], a[4], tcx, phw, ZC, dz, front], sh, i, a);
      } else if ((k === "T")) {
        phw = Math.max(thw, Math.max(Math.abs((b[0] - tcx)), Math.abs((b[2] - tcx))));
        so = _solid("wrap", [tcx, phw, ZC, F((tdz * 118), 100), 0], sh, i, a);
      } else if ((k === "E")) {
        if ((f === "pauldrons")) {
          so = _solid("ell", [a[0], a[1], (arm_z - F((tdz * 30), 100)), a[2], a[3], Math.max(half, a[2])], sh, i, a);
        } else {
          so = _solid("ell", [a[0], a[1], ZC, a[2], a[3], Math.max(half, Math.max(F((tdz * 115), 100), F((a[2] * 70), 100)))], sh, i, a);
        }
      } else if ((k === "C")) {
        so = _solid("cap", [a[0], a[1], ZC, a[2], a[3], ZC, Math.max(half, a[4])], sh, i, a);
      }
    } else if ((f === "hair")) {
      if ((k === "A")) {
        so = _solid("dome", [a[0], a[1], HZ, a[2], a[3], Math.max((hrz + half), F((a[2] * 95), 100)), a[4], F((a[3] * 60), 100)], sh, i, a);
      } else if (((k === "E")) && ((sh.z < 10))) {
        so = _solid("ell", [a[0], a[1], (HZ + F((hrz * 45), 100)), a[2], a[3], Math.max(half, F((hrz * 75), 100))], sh, i, a);
      } else if (((k === "E")) && ((sh.z < 44))) {
        so = _solid("ell", [a[0], a[1], (HZ + F((hrz * 10), 100)), a[2], a[3], Math.max(half, a[2])], sh, i, a);
      } else if ((k === "E")) {
        rz = (((a[2] < F((a[3] * 50), 100))) ? Math.max(a[2], F((hrz * 70), 100)) : a[2]);
        so = _solid("ell", [a[0], a[1], (HZ + F((hrz * 25), 100)), a[2], a[3], Math.max(half, rz)], sh, i, a);
      } else if ((k === "T")) {
        so = _solid("slab", [(HZ - F((hrz * 55), 100)), (HZ + F((hrz * 55), 100))], sh, i, a);
      } else if (((k === "C")) && ((sh.z < 10))) {
        so = _solid("cap", [a[0], a[1], (HZ + F((hrz * 60), 100)), a[2], a[3], (HZ + F((hrz * 95), 100)), Math.max(half, a[4])], sh, i, a);
      } else if ((k === "C")) {
        so = _solid("cap", [a[0], a[1], (HZ - F((hrz * 40), 100)), a[2], a[3], (HZ - F((hrz * 40), 100)), Math.max(half, a[4])], sh, i, a);
      }
    } else if (HEADWEAR_FEATS.includes(f)) {
      if (((k === "A")) && ((a[5] === (-1)))) {
        hw = g["headwear"];
        drop = ((((hw === "hood")) || ((hw === "headscarf"))) ? 95 : (((hw === "helm")) ? 60 : (((hw === "cap")) ? 20 : 0)));
        so = _solid("dome", [a[0], a[1], HZ, a[2], a[3], Math.max((hrz + (2 * half)), F((a[2] * 97), 100)), a[4], F((a[3] * drop), 100)], sh, i, a);
      } else if (((k === "R")) && ((w >= hrx))) {
        phw = Math.max(hrx, Math.max(Math.abs((a[0] - hcx)), Math.abs((a[2] - hcx))));
        so = _solid("pill", [a[0], a[1], a[2], a[3], a[4], hcx, phw, HZ, Math.max(half, F((hrz * 108), 100)), 0], sh, i, a);
      } else if (((k === "E")) && ((cy < (hcy - hry)))) {
        so = _solid("ell", [a[0], a[1], HZ, a[2], a[3], Math.max(half, a[2])], sh, i, a);
      } else if ((k === "C")) {
        so = _solid("cap", [a[0], a[1], HZ, a[2], a[3], HZ, Math.max(half, a[4])], sh, i, a);
      } else if (((k === "T")) && ((cy < (hcy - F((hry * 80), 100))))) {
        so = _solid("slab", [(HZ - F((hrz * 40), 100)), (HZ + F((hrz * 40), 100))], sh, i, a);
      } else {
        fronts.push(i);
        continue;
      }
    } else if (((f === "back")) || ((f === "back.large"))) {
      if (((k === "T")) && ((f === "back.large"))) {
        so = _solid("slab", [(back0 + half), ((back0 + half) + Math.max(px, F((tdz * 15), 100)))], sh, i, a);
      } else if ((k === "T")) {
        so = _solid("slab", [((back0 + F((tw * 13), 100)) - half), ((back0 + F((tw * 13), 100)) + half)], sh, i, a);
      } else if ((k === "R")) {
        dz = Math.max(half, F((w * 35), 100));
        so = _solid("pill", [a[0], a[1], a[2], a[3], a[4], cx, Math.max(1, F(w, 2)), (back0 + dz), dz, 0], sh, i, a);
      } else if ((k === "C")) {
        so = _solid("cap", [a[0], a[1], (back0 + a[4]), a[2], a[3], (back0 + a[4]), Math.max(half, a[4])], sh, i, a);
      } else if (((k === "E")) && ((g["back"] === "fur"))) {
        so = _solid("ell", [a[0], a[1], (ZC + F((tdz * 40), 100)), a[2], a[3], Math.max(F((tdz * 110), 100), F((a[2] * 60), 100))], sh, i, a);
      } else if ((k === "E")) {
        so = _solid("ell", [a[0], a[1], (back0 + a[2]), a[2], a[3], Math.max(half, a[2])], sh, i, a);
      }
    } else if (((f === "held")) || ((f === "held.large"))) {
      kind = (((side < 0)) ? g["held"] : g["offhand"]);
      pct = get(HELD_DEPTH, kind, 100);
      hz = ((arm_z + arm_dz) - F((tw * 7), 100));
      j = _host(solids, cx, cy, sh.z);
      if (((j >= 0)) && (["torso", "top", "bottom", "belt"].includes(solids[j]["feat"]))) {
        depth = (((k !== "C")) ? F((Math.min(w, h) * pct), 200) : a[4]);
        hz = Math.min(hz, ((front_z(solids[j], cx, cy, hz) - depth) - half));
      }
      if ((k === "C")) {
        so = _solid("cap", [a[0], a[1], hz, a[2], a[3], hz, Math.max(half, a[4])], sh, i, a);
      } else if ((k === "R")) {
        so = _solid("pill", [a[0], a[1], a[2], a[3], a[4], cx, Math.max(1, F(w, 2)), hz, Math.max(half, F((Math.min(w, h) * pct), 200)), 0], sh, i, a);
      } else if ((k === "E")) {
        so = _solid("ell", [a[0], a[1], hz, a[2], a[3], Math.max(half, F((Math.min(a[2], a[3]) * pct), 100))], sh, i, a);
      } else if ((k === "T")) {
        t = Math.max(half, F((Math.min(w, h) * 8), 100));
        so = _solid("slab", [(hz - t), (hz + t)], sh, i, a);
      } else if ((k === "A")) {
        t = Math.max(half, F((Math.min(w, h) * 10), 100));
        so = _solid("slab", [(hz - t), (hz + t)], sh, i, a);
      }
    } else {
      fronts.push(i);
      continue;
    }
    if ((so !== null)) {
      so["box"] = _box3(so);
      solids.push(so);
    }
  }
  for (n = 0, _e11 = fronts.length; n < _e11; n += 1) {
    i = fronts[n];
    sh = shapes[i];
    a = _snap(sh, half);
    k = sh.kind;
    b = _bbox(k, a);
    cx = F((b[0] + b[2]), 2);
    cy = F((b[1] + b[3]), 2);
    w = (b[2] - b[0]);
    h = (b[3] - b[1]);
    j = _host(solids, cx, cy, sh.z);
    zs = (HZ - F((hrz * 50), 100));
    if ((j >= 0)) {
      zs = front_z(solids[j], cx, cy, zs);
    }
    so = null;
    if ((k === "E")) {
      rz = (((sh.feat === "nose")) ? F((Math.max(a[2], a[3]) * 11), 10) : Math.max(half, F((Math.min(a[2], a[3]) * 60), 100)));
      so = _solid("ell", [a[0], a[1], zs, a[2], a[3], Math.max(half, rz)], sh, i, a);
    } else if ((k === "R")) {
      so = _solid("pill", [a[0], a[1], a[2], a[3], a[4], cx, Math.max(1, F(w, 2)), zs, Math.max(half, F((Math.min(w, h) * 30), 100)), 0], sh, i, a);
    } else if ((k === "C")) {
      so = _solid("cap", [a[0], a[1], (zs - half), a[2], a[3], (zs - half), Math.max(half, a[4])], sh, i, a);
    } else if ((k === "T")) {
      t = Math.max(half, F((Math.min(w, h) * 20), 100));
      so = _solid("slab", [(zs - t), (zs + t)], sh, i, a);
    } else {
      so = _solid("slab", [(zs - (2 * half)), zs], sh, i, a);
    }
    so["box"] = _box3(so);
    solids.push(so);
  }
  order = [];
  for (i = 0, _e12 = solids.length; i < _e12; i += 1) {
    j = order.length;
    while (((j > 0)) && (((order[(j - 1)]["layer"] > solids[i]["layer"])) || (((order[(j - 1)]["layer"] === solids[i]["layer"])) && ((order[(j - 1)]["idx"] > solids[i]["idx"]))))) {
      j -= 1;
    }
    order.splice(j, 0, solids[i]);
  }
  return [order, decals];
}

function _shift2(k2, a2, dx, dy) {
  let b;
  b = Array.from(a2);
  if (((k2 === "E")) || ((k2 === "A"))) {
    b[0] += dx;
    b[1] += dy;
  } else if ((k2 === "T")) {
    b[0] += dx;
    b[1] += dy;
    b[2] += dx;
    b[3] += dy;
    b[4] += dx;
    b[5] += dy;
  } else {
    b[0] += dx;
    b[1] += dy;
    b[2] += dx;
    b[3] += dy;
  }
  return b;
}

function move(so, dx, dy, dz) {
  let out, a, k;
  out = Object.assign({}, so);
  out["a2"] = _shift2(so["k2"], so["a2"], dx, dy);
  if ((get(so, "cx", null) !== null)) {
    out["cx"] = (so["cx"] + dx);
    out["cy"] = (so["cy"] + dy);
  }
  if ((get(so, "k", null) === null)) {
    return out;
  }
  a = Array.from(so["a"]);
  k = so["k"];
  if (((k === "ell")) || ((k === "dome"))) {
    a[0] += dx;
    a[1] += dy;
    a[2] += dz;
  } else if ((k === "cap")) {
    a[0] += dx;
    a[1] += dy;
    a[2] += dz;
    a[3] += dx;
    a[4] += dy;
    a[5] += dz;
  } else if ((k === "pill")) {
    a[0] += dx;
    a[1] += dy;
    a[2] += dx;
    a[3] += dy;
    a[5] += dx;
    a[7] += dz;
  } else if ((k === "wrap")) {
    a[0] += dx;
    a[2] += dz;
  } else {
    a[0] += dz;
    a[1] += dz;
    if ((a.length > 2)) {
      a[2] += dx;
    }
  }
  out["a"] = a;
  out["box"] = _box3(out);
  return out;
}

function voxelize(solids, n, extent) {
  let vs, grid, si, so, b, x0, x1, y0, y1, z0, z1, mark, yi, yc, xi, xc, c, p, zi, lo, hi, zc, _e13, _e14, _e15, _e16, _e17;
  if ((solids.length > 254)) {
    throw new Error("too many solids for one voxel grid (254 at most)");
  }
  vs = F(extent, n);
  grid = new Uint8Array(((n * n) * n));
  for (si = 0, _e13 = solids.length; si < _e13; si += 1) {
    so = solids[si];
    b = so["box"];
    [x0, x1] = [Math.max(0, F(b[0], vs)), Math.min((n - 1), F(b[3], vs))];
    [y0, y1] = [Math.max(0, F(b[1], vs)), Math.min((n - 1), F(b[4], vs))];
    [z0, z1] = [Math.max(0, F(b[2], vs)), Math.min((n - 1), F(b[5], vs))];
    mark = (si + 1);
    for (yi = y0, _e14 = (y1 + 1); yi < _e14; yi += 1) {
      yc = ((yi * vs) + F(vs, 2));
      for (xi = x0, _e15 = (x1 + 1); xi < _e15; xi += 1) {
        xc = ((xi * vs) + F(vs, 2));
        if ((so["k"] === "cap")) {
          for (zi = z0, _e16 = (z1 + 1); zi < _e16; zi += 1) {
            if (_in_cap(so["a"], xc, yc, ((zi * vs) + F(vs, 2)))) {
              grid[((((zi * n) + yi) * n) + xi)] = mark;
            }
          }
          continue;
        }
        c = _column(so, xc, yc);
        p = 0;
        while ((p < c.length)) {
          [lo, hi] = [c[p], c[(p + 1)]];
          for (zi = Math.max(z0, F(lo, vs)), _e17 = (Math.min(z1, F(hi, vs)) + 1); zi < _e17; zi += 1) {
            zc = ((zi * vs) + F(vs, 2));
            if (((lo <= zc)) && ((zc <= hi))) {
              grid[((((zi * n) + yi) * n) + xi)] = mark;
            }
          }
          p += 2;
        }
      }
    }
  }
  return grid;
}

function occupied_box(grid, n) {
  let x0, y0, z0, x1, y1, z1, zi, yi, base, xi, _e18, _e19, _e20;
  [x0, y0, z0, x1, y1, z1] = [n, n, n, (-1), (-1), (-1)];
  for (zi = 0, _e18 = n; zi < _e18; zi += 1) {
    for (yi = 0, _e19 = n; yi < _e19; yi += 1) {
      base = (((zi * n) + yi) * n);
      for (xi = 0, _e20 = n; xi < _e20; xi += 1) {
        if (grid[(base + xi)]) {
          if ((xi < x0)) {
            x0 = xi;
          }
          if ((xi > x1)) {
            x1 = xi;
          }
          if ((yi < y0)) {
            y0 = yi;
          }
          if ((yi > y1)) {
            y1 = yi;
          }
          if ((zi < z0)) {
            z0 = zi;
          }
          if ((zi > z1)) {
            z1 = zi;
          }
        }
      }
    }
  }
  if ((x1 < 0)) {
    return [];
  }
  return [x0, y0, z0, x1, y1, z1];
}

function camera(yaw, pitch) {
  let sy, cy_, sp, cp, r, d, f;
  [sy, cy_, sp, cp] = [isin(yaw), icos(yaw), isin(pitch), icos(pitch)];
  r = [cy_, 0, sy];
  d = [F((sp * sy), 4096), cp, (-F((sp * cy_), 4096))];
  f = [(-F((cp * sy), 4096)), sp, F((cp * cy_), 4096)];
  return [r, d, f];
}

function canvas_size(n, pitch) {
  if ((MOD(pitch, 90) === 0)) {
    return [n, n];
  }
  return [n, F(((n * (Math.abs(icos(pitch)) + Math.abs(isin(pitch)))) + 4095), 4096)];
}

function trace(grid, n, extent, yaw, pitch, box) {
  let vs, W, H, r, d, f, half, hit, vox, dist, lo, hi, step, reach, row, v, col, u, o, t0, t1, ok, ax, t, x, y, z, ta, tb, xi, yi, zi, m, p, _e21, _e22, _e23;
  vs = F(extent, n);
  [W, H] = canvas_size(n, pitch);
  [r, d, f] = camera(yaw, pitch);
  half = F(extent, 2);
  hit = new Array((W * H)).fill(0);
  vox = new Array(((W * H) * 3)).fill(0);
  dist = new Array((W * H)).fill(0);
  if ((box.length === 0)) {
    return [W, H, hit, vox, dist];
  }
  lo = [(box[0] * vs), (box[1] * vs), (box[2] * vs)];
  hi = [(((box[3] + 1) * vs) - 1), (((box[4] + 1) * vs) - 1), (((box[5] + 1) * vs) - 1)];
  step = Math.max(1, F(vs, 2));
  reach = (extent * 2);
  for (row = 0, _e21 = H; row < _e21; row += 1) {
    v = (F((((2 * row) + 1) * vs), 2) - F((H * vs), 2));
    for (col = 0, _e22 = W; col < _e22; col += 1) {
      u = (F((((2 * col) + 1) * vs), 2) - F((W * vs), 2));
      o = [(((half * 4096) + (u * r[0])) + (v * d[0])), (((half * 4096) + (u * r[1])) + (v * d[1])), (((half * 4096) + (u * r[2])) + (v * d[2]))];
      [t0, t1] = [(-reach), reach];
      ok = true;
      for (ax = 0, _e23 = 3; ax < _e23; ax += 1) {
        if ((f[ax] === 0)) {
          if (((o[ax] < (lo[ax] * 4096))) || ((o[ax] > (hi[ax] * 4096)))) {
            ok = false;
          }
        } else {
          ta = F(((lo[ax] * 4096) - o[ax]), f[ax]);
          tb = F(((hi[ax] * 4096) - o[ax]), f[ax]);
          if ((ta > tb)) {
            [ta, tb] = [tb, ta];
          }
          t0 = Math.max(t0, (ta - 1));
          t1 = Math.min(t1, (tb + 1));
        }
      }
      if ((!ok) || ((t0 > t1))) {
        continue;
      }
      t = (t0 - MOD(t0, step));
      while ((t <= t1)) {
        x = F((o[0] + (t * f[0])), 4096);
        y = F((o[1] + (t * f[1])), 4096);
        z = F((o[2] + (t * f[2])), 4096);
        if (((0 <= x)) && ((x < extent)) && ((0 <= y)) && ((y < extent)) && ((0 <= z)) && ((z < extent))) {
          [xi, yi, zi] = [F(x, vs), F(y, vs), F(z, vs)];
          m = grid[((((zi * n) + yi) * n) + xi)];
          if (m) {
            p = ((row * W) + col);
            hit[p] = m;
            vox[(p * 3)] = xi;
            vox[((p * 3) + 1)] = yi;
            vox[((p * 3) + 2)] = zi;
            dist[p] = t;
            break;
          }
        }
        t += step;
      }
    }
  }
  return [W, H, hit, vox, dist];
}

function normal(so, x, y, z) {
  let k, a, ln, x0, y0, z0, dx, dy, dz, len2, dot, qx, qy, qz, nx, ny, nz, b, hx, hy, hz;
  k = so["k"];
  a = so["a"];
  if ((k === "cap")) {
    [x0, y0, z0] = [a[0], a[1], a[2]];
    [dx, dy, dz] = [(a[3] - x0), (a[4] - y0), (a[5] - z0)];
    len2 = (((dx * dx) + (dy * dy)) + (dz * dz));
    dot = ((((x - x0) * dx) + ((y - y0) * dy)) + ((z - z0) * dz));
    [qx, qy, qz] = [x0, y0, z0];
    if (((len2 > 0)) && ((dot >= len2))) {
      [qx, qy, qz] = [a[3], a[4], a[5]];
    } else if (((len2 > 0)) && ((dot > 0))) {
      [qx, qy, qz] = [(x0 + F((dx * dot), len2)), (y0 + F((dy * dot), len2)), (z0 + F((dz * dot), len2))];
    }
    [nx, ny, nz] = [(x - qx), (y - qy), (z - qz)];
  } else {
    b = so["box"];
    [hx, hy, hz] = [Math.max(1, F((b[3] - b[0]), 2)), Math.max(1, F((b[4] - b[1]), 2)), Math.max(1, F((b[5] - b[2]), 2))];
    nx = Math.max((-1024), Math.min(1024, F(((x - F((b[0] + b[3]), 2)) * 1024), hx)));
    ny = Math.max((-1024), Math.min(1024, F(((y - F((b[1] + b[4]), 2)) * 1024), hy)));
    nz = Math.max((-1024), Math.min(1024, F(((z - F((b[2] + b[5]), 2)) * 1024), hz)));
  }
  ln = isqrt((((nx * nx) + (ny * ny)) + (nz * nz)));
  if ((ln === 0)) {
    return [0, 0, (-1024)];
  }
  return [F((nx * 1024), ln), F((ny * 1024), ln), F((nz * 1024), ln)];
}

function light_at(so, x, y, z, r, d, f) {
  let nm, nr, nd, nf;
  nm = normal(so, x, y, z);
  nr = F((((nm[0] * r[0]) + (nm[1] * r[1])) + (nm[2] * r[2])), 4096);
  nd = F((((nm[0] * d[0]) + (nm[1] * d[1])) + (nm[2] * d[2])), 4096);
  nf = F((((nm[0] * f[0]) + (nm[1] * f[1])) + (nm[2] * f[2])), 4096);
  return F(((((-nr) * 424) - (nd * 566)) - (nf * 707)), 1024);
}

function decal_at(decals, so, x, y, z) {
  let b, best, i, dc, _e24;
  b = so["box"];
  if ((z > F((b[2] + b[5]), 2))) {
    return (-1);
  }
  best = (-1);
  for (i = 0, _e24 = decals.length; i < _e24; i += 1) {
    dc = decals[i];
    if (((dc["group"] === so["group"])) && ((dc["layer"] > so["layer"])) && _inside(dc["k2"], dc["a2"], x, y)) {
      if (((best < 0)) || ((dc["layer"] > decals[best]["layer"])) || (((dc["layer"] === decals[best]["layer"])) && ((dc["idx"] > decals[best]["idx"])))) {
        best = i;
      }
    }
  }
  return best;
}

function paint(solids, decals, hit, vox, dist, W, H, n, extent, yaw, pitch, bands, dither, lens) {
  let vs, r, d, f, pix_mat, shade, row, col, p, m, so, x, y, z, mat, bias, dc, _e25, _e26;
  vs = F(extent, n);
  [r, d, f] = camera(yaw, pitch);
  pix_mat = new Array((W * H)).fill("");
  shade = new Array((W * H)).fill(0);
  for (row = 0, _e25 = H; row < _e25; row += 1) {
    for (col = 0, _e26 = W; col < _e26; col += 1) {
      p = ((row * W) + col);
      m = hit[p];
      if ((m === 0)) {
        continue;
      }
      so = solids[(m - 1)];
      x = ((vox[(p * 3)] * vs) + F(vs, 2));
      y = ((vox[((p * 3) + 1)] * vs) + F(vs, 2));
      z = ((vox[((p * 3) + 2)] * vs) + F(vs, 2));
      mat = so["mat"];
      bias = so["bias"];
      dc = decal_at(decals, so, x, y, z);
      if ((dc >= 0)) {
        mat = decals[dc]["mat"];
        bias = decals[dc]["bias"];
      }
      pix_mat[p] = mat;
      shade[p] = shade_index(light_at(so, x, y, z, r, d, f), lens[mat], bands, dither, col, row, bias);
    }
  }
  return [pix_mat, shade];
}

// ---- from pixelgoblin/gen/beast.py
const EXT = 2048;
const BX = 1024;
const BZ = 1024;
const BGROUND = 2000;
function _ell(cx, cy, cz, rx, ry, rz, mat, feat, layer, i) {
  let so;
  so = ({["k"]: "ell", ["a"]: [cx, cy, cz, Math.max(1, rx), Math.max(1, ry), Math.max(1, rz)], ["mat"]: mat, ["feat"]: feat, ["layer"]: layer, ["idx"]: i, ["bias"]: 0, ["k2"]: "E", ["a2"]: [cx, cy, Math.max(1, rx), Math.max(1, ry)], ["box"]: [0, 0, 0, 0, 0, 0], ["group"]: 1});
  so["box"] = _box3(so);
  return so;
}

function _cap(x0, y0, z0, x1, y1, z1, r, mat, feat, layer, i) {
  let so;
  so = ({["k"]: "cap", ["a"]: [x0, y0, z0, x1, y1, z1, Math.max(1, r)], ["mat"]: mat, ["feat"]: feat, ["layer"]: layer, ["idx"]: i, ["bias"]: 0, ["k2"]: "C", ["a2"]: [x0, y0, x1, y1, Math.max(1, r)], ["box"]: [0, 0, 0, 0, 0, 0], ["group"]: 1});
  so["box"] = _box3(so);
  return so;
}

function beast_solids(bg, px, pose, prefix) {
  let half, s, L, Hh, G, wolf, bob, stride, leg_len, ry, cy, rz, cz, fur, hide, top, lr, sx, hd, hz, hy, sn, sz, sy, er, fz, ex, ey, ez, x0, y0, tl, n, k, z0, dz, x, tx, z, _e27;
  half = F(px, 2);
  s = [];
  [L, Hh, G] = [bg["length"], bg["height"], bg["girth"]];
  wolf = ((bg["kind"] === "wolf"));
  bob = (get(pose, "bob", 0) * px);
  stride = ((get(pose, "stride", 0) * px) * 3);
  leg_len = F((Hh * 50), 100);
  ry = (F(((Hh - leg_len) * 55), 100) + 20);
  cy = ((((BGROUND - leg_len) - ry) + 40) + bob);
  rz = F(L, 2);
  cz = (BZ + F((L * 8), 100));
  fur = (prefix + "hair");
  hide = (prefix + "fur");
  s.push(_ell(BX, cy, cz, G, ry, rz, hide, "body", 1, s.length));
  if (wolf) {
    s.push(_ell(BX, (cy - F((ry * 10), 100)), (cz - F((rz * 50), 100)), F((G * 95), 100), F((ry * 110), 100), F((rz * 45), 100), hide, "body", 2, s.length));
  } else {
    s.push(_ell(BX, (cy - F((ry * 20), 100)), (cz - F((rz * 45), 100)), F((G * 105), 100), F((ry * 115), 100), F((rz * 55), 100), hide, "body", 2, s.length));
  }
  top = (cy - ry);
  lr = Math.max(half, F((G * 20), 100));
  for (sx of [(-1), 1]) {
    for (fz of [(-1), 1]) {
      z0 = (((fz < 0)) ? (cz - F((rz * 58), 100)) : (cz + F((rz * 62), 100)));
      dz = ((stride * sx) * fz);
      x = (BX + F(((sx * G) * 62), 100));
      s.push(_cap(x, (cy + F((ry * 30), 100)), z0, x, (BGROUND - lr), (z0 + dz), lr, hide, "legs", 3, s.length));
      s.push(_ell(x, (BGROUND - F((lr * 60), 100)), ((z0 + dz) - F((lr * 30), 100)), F((lr * 120), 100), F((lr * 70), 100), F((lr * 140), 100), (prefix + "hoof"), "feet", 4, s.length));
    }
  }
  hd = bg["head"];
  hz = ((cz - rz) - F((hd * 35), 100));
  hy = ((wolf ? (top + F((hd * 40), 100)) : (cy - F((ry * 15), 100))) + bob);
  s.push(_ell(BX, hy, hz, F((hd * 85), 100), hd, F((hd * 110), 100), hide, "head", 5, s.length));
  sn = F((bg["snout"] * (wolf ? 150 : 100)), 100);
  sz = ((hz - F((hd * 100), 100)) - F((sn * 30), 100));
  sy = (hy + F((hd * 30), 100));
  s.push(_ell(BX, sy, sz, F((sn * (wolf ? 45 : 60)), 100), F((sn * (wolf ? 40 : 55)), 100), sn, (prefix + "skin"), "nose", 6, s.length));
  s.push(_ell(BX, (sy - F((sn * 5), 100)), (sz - F((sn * 90), 100)), F((sn * 30), 100), F((sn * 25), 100), Math.max(half, F((sn * 15), 100)), (prefix + "mouth"), "nose", 7, s.length));
  for (sx of [(-1), 1]) {
    [ex, ey, ez] = [(BX + F(((sx * hd) * 45), 100)), (hy - F((hd * 25), 100)), (hz - F((hd * 70), 100))];
    s.push(_ell(ex, ey, ez, Math.max(half, F((hd * 16), 100)), Math.max(half, F((hd * 14), 100)), Math.max(half, F((hd * 12), 100)), (prefix + "eye_white"), "eyes", 8, s.length));
    s.push(_ell(ex, ey, (ez - F((hd * 6), 100)), Math.max(half, F((hd * 10), 100)), Math.max(half, F((hd * 10), 100)), Math.max(half, F((hd * 10), 100)), (prefix + "iris"), "eyes", 9, s.length));
  }
  er = bg["ear"];
  for (sx of [(-1), 1]) {
    [x0, y0] = [(BX + F(((sx * hd) * 40), 100)), (hy - F((hd * 80), 100))];
    if (wolf) {
      s.push(_cap(x0, y0, hz, (x0 + F(((sx * er) * 20), 100)), (y0 - er), (hz + F((er * 15), 100)), Math.max(half, F((er * 25), 100)), hide, "ears", 8, s.length));
    } else {
      s.push(_cap(x0, y0, hz, (x0 + F(((sx * er) * 80), 100)), (y0 - F((er * 20), 100)), (hz + F((er * 30), 100)), Math.max(half, F((er * 30), 100)), hide, "ears", 8, s.length));
    }
  }
  if (bg["tusks"]) {
    for (sx of [(-1), 1]) {
      tx = (BX + F(((sx * sn) * 45), 100));
      s.push(_cap(tx, (sy + F((sn * 20), 100)), (sz - F((sn * 40), 100)), (tx + F(((sx * sn) * 25), 100)), (sy - F((sn * 55), 100)), (sz - F((sn * 70), 100)), Math.max(half, F((sn * 10), 100)), (prefix + "teeth"), "tusks", 9, s.length));
    }
  }
  if (wolf) {
    s.push(_ell(BX, (hy + F((hd * 60), 100)), (hz + F((hd * 70), 100)), F((G * 90), 100), F((hd * 90), 100), F((hd * 80), 100), fur, "hair", 4, s.length));
    tl = F((bg["tail"] * 150), 100);
    s.push(_ell(BX, (cy - F((ry * 10), 100)), ((cz + rz) + F((tl * 50), 100)), Math.max(half, F((tl * 25), 100)), Math.max(half, F((tl * 30), 100)), F((tl * 60), 100), fur, "tail", 4, s.length));
  } else {
    n = 5;
    for (k = 0, _e27 = n; k < _e27; k += 1) {
      z = ((hz + F((hd * 60), 100)) + F(((k * rz) * 22), 100));
      s.push(_cap(BX, ((top + F((ry * 10), 100)) - F(bob, 2)), z, BX, (top - F((bg["ear"] * 60), 100)), (z + F((rz * 8), 100)), Math.max(half, F((G * 12), 100)), fur, "hair", 4, s.length));
    }
    tl = bg["tail"];
    s.push(_cap(BX, (cy - F((ry * 40), 100)), (cz + rz), BX, (cy + F((ry * 10), 100)), ((cz + rz) + tl), Math.max(half, F((G * 6), 100)), hide, "tail", 4, s.length));
  }
  if (bg["saddle"]) {
    s.push(_ell(BX, (top + F((ry * 12), 100)), (cz - F((rz * 15), 100)), F((G * 104), 100), F((ry * 35), 100), F((rz * 42), 100), (prefix + "cloth_a"), "top", 6, s.length));
    s.push(_ell(BX, (top - 10), (cz - F((rz * 15), 100)), F((G * 70), 100), Math.max(half, F((ry * 18), 100)), F((rz * 30), 100), (prefix + "leather"), "top", 7, s.length));
    for (sx of [(-1), 1]) {
      x = (BX + F(((sx * G) * 100), 100));
      s.push(_cap(x, (top + F((ry * 10), 100)), (cz - F((rz * 15), 100)), x, (cy + F((ry * 60), 100)), (cz - F((rz * 15), 100)), Math.max(half, px), (prefix + "leather"), "straps", 7, s.length));
      s.push(_ell(x, (cy + F((ry * 65), 100)), (cz - F((rz * 15), 100)), Math.max(half, F((G * 12), 100)), Math.max(half, F((G * 8), 100)), Math.max(half, F((G * 10), 100)), (prefix + "metal"), "held", 8, s.length));
    }
  }
  return s;
}

function seat(bg) {
  let L, Hh, leg_len, ry, cy;
  [L, Hh] = [bg["length"], bg["height"]];
  leg_len = F((Hh * 50), 100);
  ry = (F(((Hh - leg_len) * 55), 100) + 20);
  cy = (((BGROUND - leg_len) - ry) + 40);
  return [BX, ((cy - ry) - 30), ((BZ + F((L * 8), 100)) - F((F(L, 2) * 15), 100))];
}

function seat_rider(solids, decals, bg, px) {
  let hip_y, hip_x, leg_r, so, at, dx, dy, dz, out, G, span, sx, moved, dc, hx, kx, kz, ky, thigh, fy, shin, boot, a;
  hip_y = 0;
  hip_x = 0;
  leg_r = px;
  for (so of solids) {
    if ((so["feat"] === "legs")) {
      a = so["a"];
      hip_y = Math.max(hip_y, Math.min(a[1], a[4]));
      hip_x = Math.max(hip_x, Math.abs((a[0] - 512)));
      leg_r = Math.max(leg_r, a[6]);
    }
  }
  at = seat(bg);
  [dx, dy, dz] = [(at[0] - 512), (at[1] - hip_y), (at[2] - 512)];
  out = [];
  for (so of solids) {
    if (((so["feat"] === "legs")) || ((so["feat"] === "feet")) || (((so["feat"] === "bottom")) && ((so["k"] === "cap")))) {
      continue;
    }
    out.push(move(so, dx, dy, dz));
  }
  G = bg["girth"];
  span = Math.max(hip_x, (G + leg_r));
  for (sx of [(-1), 1]) {
    hx = (at[0] + (sx * hip_x));
    kx = (at[0] + (sx * span));
    kz = (at[2] - (leg_r * 5));
    ky = (at[1] + (leg_r * 2));
    thigh = ({["k"]: "cap", ["a"]: [hx, at[1], at[2], kx, ky, kz, F((leg_r * 12), 10)], ["mat"]: "cloth_b", ["feat"]: "bottom", ["layer"]: 14, ["idx"]: (900 + sx), ["bias"]: 0, ["k2"]: "C", ["a2"]: [hx, at[1], kx, ky, F((leg_r * 12), 10)], ["box"]: [0, 0, 0, 0, 0, 0], ["group"]: 0});
    thigh["box"] = _box3(thigh);
    out.push(thigh);
    fy = (ky + (leg_r * 5));
    shin = ({["k"]: "cap", ["a"]: [kx, ky, kz, kx, fy, (kz + leg_r), leg_r], ["mat"]: "skin", ["feat"]: "legs", ["layer"]: 10, ["idx"]: (910 + sx), ["bias"]: 0, ["k2"]: "C", ["a2"]: [kx, ky, kx, fy, leg_r], ["box"]: [0, 0, 0, 0, 0, 0], ["group"]: 0});
    shin["box"] = _box3(shin);
    out.push(shin);
    boot = ({["k"]: "ell", ["a"]: [kx, fy, kz, F((leg_r * 14), 10), leg_r, (leg_r * 2)], ["mat"]: "leather", ["feat"]: "feet", ["layer"]: 12, ["idx"]: (920 + sx), ["bias"]: 0, ["k2"]: "E", ["a2"]: [kx, fy, F((leg_r * 14), 10), leg_r], ["box"]: [0, 0, 0, 0, 0, 0], ["group"]: 0});
    boot["box"] = _box3(boot);
    out.push(boot);
  }
  moved = [];
  for (dc of decals) {
    moved.push(move(dc, dx, dy, dz));
  }
  return [out, moved];
}
