#!/usr/bin/env python3
"""Build editor/pixelgoblin.html from editor/src.html.

Embeds the exact engine script (editor/pg-core.js, then editor/pg-rig.js with
the geometry generated by tools/transpile_rig.py spliced in; gate B13 checks
it) and every type file on the search path, resolved by the Python engine, so
the page runs fully offline as one file. Overlay types (subspecies) also carry
their OWN keys, because typefile.compose applies only those.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from pixelgoblin import CREDIT, VERSION, typefile  # noqa: E402


def engine_script() -> str:
    ed = ROOT / "editor"
    rig = (ed / "pg-rig.js").read_text().replace("/*__RIG_GEN__*/", (ed / "pg-rig.gen.js").read_text())
    return (ed / "pg-core.js").read_text() + "\n" + rig


def main() -> int:
    types = []
    for root in typefile.search_path():
        for p in typefile.type_files(root):
            tf = typefile.load(p)
            entry = {"data": tf.data, "flavor": not tf.id.startswith("vanilla."), "hash": tf.type_hash}
            if ".sub." in tf.id:
                entry["own"] = typefile._read_toml(p)
            types.append(entry)
    tax = typefile.taxonomy()
    tags = [{"name": name, "profile": typefile.profile_for(name)} for name in tax.get("tag", {})]
    from pixelgoblin import city
    cities = []
    for root in typefile.search_path():
        for cp in sorted(Path(root).rglob("*.city.toml")):
            d = city.load_city(str(cp))
            d.pop("_hash", None)
            names = cp.with_name(cp.name.replace(".city.toml", ".names.txt"))
            cities.append({"data": d, "names": names.read_text() if names.exists() else ""})
    presets = {"version": VERSION, "credit": CREDIT, "types": types, "tags": tags, "teams": typefile.teams(), "cities": cities}
    src = (ROOT / "editor" / "src.html").read_text()
    html = src.replace("/*__PG_CORE__*/", engine_script()).replace("/*__PRESETS__*/", json.dumps(presets, ensure_ascii=False))
    (ROOT / "editor" / "pixelgoblin.html").write_text(html)
    print(f"editor/pixelgoblin.html  {len(html) // 1024} KB  {len(types)} types  {len(tags)} tag profiles")
    return 0


if __name__ == "__main__":
    sys.exit(main())
