#!/usr/bin/env python3
"""Build editor/pixelgoblin.html (the workbench), editor/pixelgoblin-pocket.html
(the pocket widget) and editor/pixelgoblin-grounds.html (Goblin Grounds) from their src files.

Embeds the exact engine script (editor/pg-core.js, then editor/pg-rig.js with
the geometry generated by tools/transpile_rig.py spliced in; gate B13 checks
it) and every type file on the search path, resolved by the Python engine, so
the page runs fully offline as one file. Overlay types (subspecies) also carry
their OWN keys, because typefile.compose applies only those.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from pixelgoblin import CREDIT, VERSION, typefile  # noqa: E402


def engine_script() -> str:
    ed = ROOT / "editor"
    rig = (ed / "pg-rig.js").read_text(encoding="utf-8").replace("/*__RIG_GEN__*/", (ed / "pg-rig.gen.js").read_text(encoding="utf-8"))
    return (ed / "pg-core.js").read_text(encoding="utf-8") + "\n" + rig


def main() -> int:
    types = []
    for root in typefile.search_path():
        for p in typefile.type_files(root):
            tf = typefile.load(p)
            entry = {"data": tf.data, "flavor": not tf.id.startswith("vanilla."), "hash": tf.type_hash}
            if ".sub." in tf.id:
                entry["own"] = typefile._read_toml(p)
            types.append(entry)
    tax = typefile.taxonomy()
    tags = [{"name": name, "profile": typefile.profile_for(name)} for name in tax.get("tag", {})]
    from pixelgoblin import city
    cities = []
    for root in typefile.search_path():
        for cp in sorted(Path(root).rglob("*.city.toml")):
            d = city.load_city(str(cp))
            d.pop("_hash", None)
            names = cp.with_name(cp.name.replace(".city.toml", ".names.txt"))
            cities.append({"data": d, "names": names.read_text(encoding="utf-8") if names.exists() else ""})
    packs = [{k: v for k, v in pk.items() if k != "path"} for pk in typefile.packs()]
    souls = []
    for root in typefile.search_path():
        for f in sorted(Path(root).rglob("souls.toml")):
            souls += typefile._read_toml(f).get("entities", [])
    presets = {"version": VERSION, "credit": CREDIT, "types": types, "tags": tags, "teams": typefile.teams(), "cities": cities, "packs": packs, "souls": souls}
    eng = engine_script()
    pocket = dict(presets, types=[t for t in types if t["data"].get("generator") in ("rig", "beast")])
    for src_name, out_name, pre in (("src.html", "pixelgoblin.html", presets), ("widget.src.html", "pixelgoblin-pocket.html", pocket),
                                    ("grounds.src.html", "pixelgoblin-grounds.html", presets)):
        src = (ROOT / "editor" / src_name).read_text(encoding="utf-8")
        html = src.replace("/*__PG_CORE__*/", eng).replace("/*__PRESETS__*/", json.dumps(pre, ensure_ascii=False))
        (ROOT / "editor" / out_name).write_text(html, encoding="utf-8")
        print(f"editor/{out_name}  {len(html) // 1024} KB  {len(pre['types'])} types  {len(tags)} tag profiles")
    return 0


if __name__ == "__main__":
    for _s in (sys.stdout, sys.stderr):  # a pipe on Windows defaults to cp1252; write UTF-8 everywhere
        _s.reconfigure(encoding="utf-8")
    sys.exit(main())
