#!/usr/bin/env python3
"""Package PixelGoblin for Claude: the plugin (.plugin) and the PseudoSkill capsule (.skill).

usage: package.py [plugin|capsule|all]   (default all)

Hand-written parts live in packaging/plugin/ and packaging/capsule/. This script
copies the engine, pages and docs in beside them, generates the roster, and
zips the results into dist/. Mark's reference images (refs/) are never copied:
the copy works from an allowlist, and the final check refuses any refs/ path.

    —Shibbieness
    —Claude
"""
from __future__ import annotations

import json
import shutil
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from pixelgoblin import VERSION, typefile  # noqa: E402

DIST = ROOT / "dist"
PKG = ROOT / "packaging"
IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store", ".falsify_backup", "out")
ENGINE_PARTS = ["pixelgoblin", "types", "flavors", "flavor.toml", "vanilla_flavor.py", "tools/build_packs.py", "LICENSE", "NOTICE.md", "ATTRIBUTION.md", "LICENSE-COMMERCIAL.md"]
LEGAL = ["LICENSE", "NOTICE.md", "ATTRIBUTION.md", "LICENSE-COMMERCIAL.md"]
PAGES = ["pixelgoblin.html", "pixelgoblin-pocket.html", "pixelgoblin-grounds.html"]


def copy(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.is_dir():
        shutil.copytree(src, dst, ignore=IGNORE, dirs_exist_ok=True)
    else:
        shutil.copy2(src, dst)


def roster_md() -> str:
    roles, mounts, subs, other = [], [], [], []
    for root in typefile.search_path():
        for p in typefile.type_files(root):
            tf = typefile.load(p)
            lab = tf.data.get("label", "")
            if tf.generator == "rig" and ".sub." in tf.id:
                subs.append((tf.id.split(".")[-1], lab))
            elif tf.generator == "rig" and tf.data.get("role") and tf.data.get("label"):
                roles.append((tf.id, lab, ", ".join(sorted(set(tf.data["role"].get("held", [])))) or "-"))
            elif tf.generator == "beast":
                mounts.append((tf.id, lab))
            else:
                other.append((tf.id, tf.generator, lab))
    teams = typefile.teams()
    from pixelgoblin.gen import rig, rig3d
    lines = [f"# PixelGoblin roster ({VERSION})", "", "Generated by `tools/package.py` from the type files. Use the id with any command.", "",
             f"## Jobs ({len(roles)})", "", "| id | label | holds |", "|---|---|---|"]
    lines += [f"| `{i}` | {l} | {h} |" for i, l, h in sorted(roles)]
    lines += ["", f"## Mounts ({len(mounts)})", "", "| id | label |", "|---|---|"] + [f"| `{i}` | {l} |" for i, l in sorted(mounts)]
    lines += ["", f"## Clans ({len(teams)})", "", "Use with `--team`. Clans change clothes colours only.", "", "| clan | label |", "|---|---|"]
    lines += [f"| `{k}` | {v.get('label', k)} |" for k, v in sorted(teams.items())]
    lines += ["", f"## Variants ({len(subs)})", "", "Use with `--sub`.", "", "| sub | label |", "|---|---|"] + [f"| `{i}` | {l} |" for i, l in sorted(subs)]
    lines += ["", "## Views", "", "| view | turn | tilt |", "|---|---|---|"] + [f"| `{k}` | {v[0]}° | {v[1]}° |" for k, v in rig3d.VIEWS.items()]
    lines += ["", "## Sizes and eras", "", "| size | default era | colours |", "|---|---|---|"]
    lines += [f"| {t} px | {rig.DEFAULT_CHAIN[t]} | {rig.ERAS[rig.DEFAULT_CHAIN[t]]['max_colors']} |" for t in (8, 16, 32, 64, 128, 256)]
    lines += ["", "## Cities", ""] + [f"- `boc.city.{p.name.replace('.city.toml', '')}` (names file `{p.with_name(p.name.replace('.city.toml', '.names.txt')).relative_to(ROOT)}`)" for p in sorted((ROOT / "flavors").rglob("*.city.toml"))]
    lines += ["", f"## Other type files ({len(other)})", "", "| id | generator | label |", "|---|---|---|"] + [f"| `{i}` | {g} | {l} |" for i, g, l in sorted(other)]
    return "\n".join(lines) + "\n"


def build_plugin(dist: Path = DIST) -> Path:
    out = dist / "pixelgoblin"
    if out.exists():
        shutil.rmtree(out)
    copy(PKG / "plugin", out)
    for f in LEGAL:
        copy(ROOT / f, out / f)
    sk = out / "skills" / "pixelgoblin"
    for part in ENGINE_PARTS:
        copy(ROOT / part, sk / "engine" / part)
    for page in PAGES:
        copy(ROOT / "editor" / page, sk / "pages" / page)
    refs = {
        "pixelgoblin": ["reference/cli.md", "explanation/views.md", "explanation/tier-chain.md", "howto/build-a-city.md", "howto/use-resource-packs.md", "howto/play-goblin-grounds.md",
                        "howto/use-in-a-game.md", "howto/convert-an-image.md", "howto/make-a-ui-kit.md"],
        "pixelgoblin-types": ["reference/type-files.md", "tutorials/make-a-species.md"],
        "pixelgoblin-engine": ["explanation/decisions.md", "explanation/gates.md", "explanation/stack.md",
                               "explanation/determinism.md", "explanation/gameplan.md"],
    }
    for skill, docs in refs.items():
        for d in docs:
            copy(ROOT / "docs" / d, out / "skills" / skill / "references" / Path(d).name)
    (sk / "references" / "roster.md").write_text(roster_md())
    return out


def zip_dir(src: Path, dest: Path, root_name: str | None = None) -> Path:
    if dest.exists():
        dest.unlink()
    with zipfile.ZipFile(dest, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for p in sorted(src.rglob("*")):
            rel = p.relative_to(src)
            if "refs" in rel.parts or "__pycache__" in rel.parts or p.name == ".DS_Store":
                raise SystemExit(f"refusing to package {rel}")
            arc = (Path(root_name) / rel) if root_name else rel
            if p.is_dir():
                continue
            z.write(p, str(arc))
    return dest


def main() -> int:
    what = sys.argv[1] if len(sys.argv) > 1 else "all"
    DIST.mkdir(exist_ok=True)
    if what in ("plugin", "all"):
        d = build_plugin()
        z = zip_dir(d, DIST / "pixelgoblin.plugin")
        print(f"{z.relative_to(ROOT)}  {z.stat().st_size // 1024} KB  ({sum(1 for _ in d.rglob('*') if _.is_file())} files)")
    if what in ("capsule", "all"):
        from packaging_capsule import NAME, build_capsule  # noqa: E402  (tools/packaging_capsule.py)
        d = build_capsule(ROOT, DIST)
        z = zip_dir(d, DIST / f"{NAME}.skill", NAME)
        print(f"{z.relative_to(ROOT)}  {z.stat().st_size // 1024} KB  ({sum(1 for _ in d.rglob('*') if _.is_file())} files)")
    return 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    sys.exit(main())
